### ISSUE TITLE
Don't run purge at midnight

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#1072]
The backup process complained about missing files, because they got purged while the backup was running. Since the backup runs at midnight, don't run the purge script at midnight. According to the [SystemD docs], you should configure it like this:

    OnCalendar=*-*-* 01..23:00:00

Be sure to comment what it means and why. Also look at the schedule of the synch script.

[SystemD docs]: https://www.freedesktop.org/software/systemd/man/systemd.time.html#

**Comment by rhliang** [comment]
The synch script runs 12:00AM Mondays.  Should I change that to 11PM Sunday or 1AM Monday?

**Comment by donkirkby** [comment]
Let's go for 1AM on Monday.

**Comment by rhliang** [comment]
The purge task systemd job now avoids midnight.  For some reason the `01..23` syntax wouldn't work -- the unit would fail to parse the calendar specification -- so I brute forced it and set it to 

```
*-*-* 01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23:00:00
```

I'll change the sync script next.
