### ISSUE TITLE
Edit datasets in Single Dataset Upload Page

### ISSUE THREAD

**Issue by tnguyencfe** [cfe-lab/Kive#217]

**Comment by ArtPoon** [comment]
* Click on object name to inspect.  For example, clicking on a CodeResource currently takes you to viewing the source code.  Present metadata in editable fields.  If user wants to revise metadata, they can do so and click on "submit" button.
* From object list page, click on "revise" link to create an object revision.
* Also provide a Revise link in object inspector page.
