### ISSUE TITLE
Implement a test case using Docker to run a minimal pipeline in Kive

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#305]
It would be nice to let developers choose from a set of Docker containers to run their pipelines in, or maybe even upload new ones. This would isolate pipelines from changes to the host system, and it might be more secure to avoid giving pipeline code access to the whole host system.

However, Docker doesn't support CentOS 5, it [requires CentOS 7](https://docs.docker.com/v1.8/installation/centos/).

**Comment by donkirkby** [comment]
This issue has been replaced by #681.
