### ISSUE TITLE
Review old API remnants

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#314]
How much is left of our first attempts to build a REST API? Searching for `@api_view` will probably find a bunch.

If there's a small number of them, just convert to using the new ViewSet style of API, otherwise create issues to convert them.

* [x] remove `@api_views`
* [x] search for `@login_required` in all `ajax.py` files
* [x] Remove `@login_required` AJAX methods from the following apps:
  * [x] metadata
  * [x] method
  * [x] pipeline
  * [x] sandbox
* [x] unneeded views for downloading? See `urls.py` lines 85-94.
* [x] any other AJAX remnants?

**Comment by ArtPoon** [comment]
DataSet AJAX transaction was refactored as part of addressing issue cfe-lab/MiCall#95
