### ISSUE TITLE
Stop a run

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#325]
Add an option for a run owner or administrator to stop a run by killing the process. We should discuss whether it makes sense to let the pipeline methods clean up before shutting down, or if we should just clean up the sandbox as described in issues #201 and 309. Also stop a run when it's being removed or redacted, this currently crashes the fleet, because the run has disappeared when a fleet worker tries to update it.

It probably also makes sense to start a stopped run (not a failed run). The owner and administrators for sure, what about other users that can see the run? Should other users be able to stop runs they can see?

Should starting a stopped run create a new run with the same inputs that just reuses any completed steps? Does it make the history less confusing or more confusing? Perhaps leaving the halted RunStep records where the first run was stopped makes it easier to understand the history, so the restart should be a new run.

* [x] discuss clean up
* [x] discuss permissions
* [x] add links to ~~pause or~~ stop a run
* [x] ~~stop when removing or redacting~~
* [x] start a stopped run

**Comment by ArtPoon** [comment]
Discussion on whether to let pipeline methods clean up before shutting down:
* let Kive handle cleaning up the Sandbox (deleting intermediate files)
* have Workers poll (wait for response from child process, with a timeout, and then if no response, check for a shutdown request from the fleet manager)
* send a signal to terminate pipeline methods through the OS - this will meet due diligence as it gives the developer the opportunity to catch this signal and terminate

**Comment by ArtPoon** [comment]
Discussion on permissions:
* only administrators and owners should be able to stop a run
* if a user has access to the relevant data and Methods, then he or she should be able to restart a stopped run
* create a brand new Run object that is instantiated as a restart of a previously stopped Run - the restarting User becomes the owner of the new Run, and the previous User retains ownership of the stopped Run
* this approach utilizes the same machinery as re-doing a Run -- any completed steps will be reused from the database
* on the backend, we need a way to mark a Run as having been stopped, e.g., a `is_stopped` flag
* record the user who stopped the run

**Comment by ArtPoon** [comment]
What about if there is a power outage and a run is unintentionally stopped?  We need to be able to restart a run in this state.
Three scenarios:
1. power outage
2. stop everything
3. stop everything and start up again

(2) and (3) are identical from the back-end perspective.
Another problem is that every run that had ever been stopped would show up in a list if one wanted to restart runs after a power outage.

Propose annotating runs as being `stopped` or `paused`.  Paused runs would continue to show up in active runs.  Stopped runs would not.

**Comment by rhliang** [comment]
Stopping a Run while removing/redacting related objects may be problematic because if we remove the Run, the fleet may not receive the instruction to stop it (the instruction is simply that we set `stopped_by` in the Run).  Instead, let's continue with our current policy of not allowing people to remove things that are currently being run.

**Comment by rhliang** [comment]
After discussion with Don, let's not worry about pausing runs yet.  It seems like a "paused" run should be one that still has an active sandbox that's being tracked by the fleet, rather than a "stopped" run which has been stopped outright and whose sandbox has been forgotten.
