### ISSUE TITLE
Clarify error for missing shebang

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#335]
If the user uploads a script without a `#!/usr/bin/env ...` at the top, we get a strange error like "error #8, Exec format".
If we see that error, Kive should be more helpful and ask the user if they need to add a shebang to the script.

* [x] check for missing shebang (including override challenge)
* [x] fix CSRF problem in method forms
* [ ] check for CSRF problem in other forms
* [ ] method input, outputs are broken on resubmit

**Comment by ArtPoon** [comment]
Do the warning on creation of a method AND look into spotting the error on SSH execution.

**Comment by wrpscott** [comment]
commit a23294b closes this.
