### ISSUE TITLE
Dropping in the output zone

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#340]
When you drop an object in the pipeline revision page's output zone, it's supposed to get pushed out of the zone.

Three problems:

1. Some types of objects, such as CDT nodes and methods, don't get pushed far enough, and they hang over the edge of the output zone.
2. There's no collision detection after sliding, so objects can overlap after getting pushed out of the output zone.
3. The code that pushes the objects is the only thing using the `w` attribute on nodes. It could find the rightmost vertex and slide based on that. Then we could remove the `w` attribute. This should also fix the first problem.

* [x] switch to calculating based on vertices
* [ ] remove `w` attribute
* [x] detect collisions after pushing (not worth a lot of effort, but nice to have)

**Comment by donkirkby** [comment]
@jnak-cfe, did you complete all three items in the check list? Your commit comment only seems to cover the first one.

**Comment by jnak-cfe** [comment]
I actually took a different approach. The collision detection algorithm now treats the output zone as an immovable shape. So, the third one is also effectively done.

I suppose we can remove the w attribute now? I didn't check to confirm but I guess nothing is using it anymore.

**Comment by donkirkby** [comment]
If nothing's using it, then please remove the `w` attribute.

**Comment by jnak-cfe** [comment]
I just took a look. It's not needed for production, but for development a lot of nodes' `draw` methods use `w`. If we remove `w`, it'll be less convenient for us to alter node appearance. Are we at the stage where we're ready to cut the proverbial umbilical cord on node display options?
