### ISSUE TITLE
Outputs listed as redacted after failure

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#360]
Steps to reproduce:

1. Create a script that always fails, like this:

        #!/usr/bin/env python
        print 'Starting'
        
        exit('Bad stuff')
2. Upload it as a code resource, create a method and a pipeline to execute it.
3. Run the pipeline, and look at the results page.

Expected behaviour: the outputs show as missing or zero bytes.

Actual behaviour: the outputs show as redacted.

**Comment by ArtPoon** [comment]
With current changes, the outputs of this step would be listed as 'removed' rather than 'redacted'.  Push to next milestone.
