### ISSUE TITLE
Permissions widget should restrict revision permissions in the frontend

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#371]
Currently:
- a user can revise a method or code resource and set new permissions
- if the user tries to give the revision _more_ permitted users/groups than its parent, the widget will allow this
- when the user submits, Django raises an error

Expected:
- only users/groups which are (or are subsets of) existing permission holders populate the widget on pageload
- getting this set will require some backend logic
- using this method, the permissions widget will not be able to submit invalid selections

**Comment by donkirkby** [comment]
It looks like this got fixed, at least for containers and their families, in aaee1d5265a27fe7e59658500b186a70adab0785 as part of v0.12. If we need to do this for another form, derive from `metadata.forms.PermissionsForm` and follow the instructions about setting `access_limits`.

Closing the issue.
