### ISSUE TITLE
Updating a CodeResourceRevision that only has updated dependencies still requires a file to be uploaded

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#374]
In updating the MiSeq pipeline on Kive, I encountered several pieces of code that had no changes but whose dependencies changed.  This required me to re-upload the same piece of code.

I think a nice feature would be to automatically reuse the old file provided at least one of the dependencies changes.  Perhaps there would be a prompt confirming this action.

**Comment by donkirkby** [comment]
No longer relevant since #519 moved dependencies to the method.
