### ISSUE TITLE
Bulk data upload destroys file names

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#375]
I tried uploading a massive number of FASTQ files from a MiSeq run to Kive on Bulbasaur, as a sort of stress test (and also because this is a representative task).  All filenames were lost.  Is this expected behaviour?

**Comment by jjh13** [comment]
This is the expected behaviour (according to the code). The naming scheme works like this:
If no name prefix is given, then the data set name will be the filename + "_" + a datetime string, otherwise the data set name will be name_prefix + "_" + datetime string. 

Is that what we want?

**Comment by donkirkby** [comment]
I'm pretty sure we don't want to upload 100 files and end up with datasets whose names only vary by a time stamp. I had assumed that `name_prefix` would be added before the file name. That way, you could always make the data set name `name_prefix + "_" + filename + "_" + datetime`. Drop the leading underscore if `name_prefix` is blank.
