### ISSUE TITLE
Remove/streamline circular dependencies

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#379]
Motivation is to allow squash migrations to work (see issue #296) and to reduce confusion among developers.
- [x] RunToProcess, Run
- [x] SymbolicDataset, Dataset
- [ ] ExecRecord, ExecLog

**Comment by rhliang** [comment]
I'm going to take on RunToProcess and Run for now while I work on #325.

**Comment by rhliang** [comment]
I'll (attempt) merging SymbolicDataset and Dataset as part of working on #217.

**Comment by rhliang** [comment]
SymbolicDataset and Dataset are now merged in the CombineDSSD branch, which will eventually become the master branch.
