### ISSUE TITLE
Line limit on dataset viewer

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#386]
If we try to view a very large dataset, the apache process runs and runs, using more and more memory. We think this bogged down the whole server.

Just add a limit of 100 or 1000 lines. Think about what to do with a file that has a failed data check on the 5000th line.

* [x] add the limit (this will prevent our server from choking)
* [x] don't scan the file for errors every time, load from the database
* [ ] figure out a plan for the errors beyond the line limit

**Comment by rhliang** [comment]
Limit hasn't been implemented yet, but much of the slowness was a result of a huge number of database hits (one for each cell).  A prefetch has improved the performance greatly.

**Comment by ArtPoon** [comment]
To elaborate on the problem with errors, if there is an error on line 999 but we are only displaying the first 100, then how is this indicated to the user?

**Comment by ArtPoon** [comment]
See also #478 regarding viewing binary files.
