### ISSUE TITLE
Pipeline selection pulldown on the Analysis page should be filtered by user permissions

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#390]
At the moment, the pulldown shows all revisions, but when you attempt to start a new Run from a Pipeline that you don't have permission on, you get a 404.

**Comment by ArtPoon** [comment]
To elaborate: A developer should be able to see all versions of a pipeline that they have access permissions to.  A regular (non-developer) user will only see published versions they have permissions granted for.

**Comment by ArtPoon** [comment]
Possible duplicate of previously closed issue.  RL will investigate.

**Comment by rhliang** [comment]
Not a duplicate, but this should have been lumped in with #401, #404, and #407.  It was fixed at the same time, so I'm closing this issue.
