### ISSUE TITLE
Indicate errors produced when a run fails on the View Run page and/or the View Results page

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#391]
Presently when a step fails, it gets highlighted in red and you can view the log and error log.  However these logs are sometimes not helpful, and we have more helpful information on the backend that we aren't displaying at all yet.  We should discuss a good way to display at least some of this information to assist in debugging of pipelines.

* [ ] Highlight the failed step in red, along with the magnets and cables for any outputs that failed data checks.
* [ ] Add entries to the method's pop-up menu for the return code (grayed out) and to view all the outputs (including check mark or cross).
* [x] Add column for return code to run results page, plus a check mark or cross after each output name.
* [x] Display a question mark for each output that didn't have its content checked because another output failed.
* [x] Either display something for quarantined runs to show which check failed, or create a separate issue.

**Comment by donkirkby** [comment]
After a discussion, we decided on the following changes:
* Highlight the failed step in red, along with the magnets and cables for any outputs that failed data checks.
* Add entries to the method's pop-up menu for the return code (grayed out) and to view all the outputs (including check mark or cross).
* Add column for return code to run results page, plus a check mark or cross after each output name.

**Comment by rhliang** [comment]
Another issue I've had when testing out new code is that the fleet crashes (due to bugs in the code that will be ironed out), but I can't remove the Run that failed.  From the shell, I get this message:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/kive/fleet/models.py", line 235, in remove
    metadata.models.remove_helper(removal_plan)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/rliang/Documents/Research/Copperfish/copperfish/kive/metadata/models.py", line 67, in remove_helper
    raise RTPNotFinished("Cannot remove: an affected run is still in progress")
RTPNotFinished: Cannot remove: an affected run is still in progress
```

**Comment by ArtPoon** [comment]
`&cross;` and `&check;` are supported as part of HTML5 to produce glyphs for "cross" &cross; and "checkmark" &check; respectively.

**Comment by donkirkby** [comment]
The view run page with the pipeline diagram is currently built from data on the run steps, and the view results page is built from data on the step outputs.
I've made the changes to display which outputs have failed on the view results page, but that data isn't currently available to the view run page. There's a link from one page to the other, so I suggest we try the current version before making bigger changes.
I'm going to close this issue, and we can make another issue if we decide we really want to see output details on the view run page.
