### ISSUE TITLE
Prepopulate name field when uploading a data set with the filename

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#400]
* [ ] when you upload a data set, the `Name` field should be populated by the file name as the default value.  This provides feedback that the user has uploaded the file they intended to upload.
* [x] ~~user should be able to edit data set name and description when they have entered incorrect text~~ duplicate of #217
* [x] ~~when a run is complete, there is no link that will take you immediately to the pipeline results.  The "Complete" status should link to this page.~~

**Comment by rhliang** [comment]
The third point is implemented but perhaps has a Heisenbug in it.  See issue #389.

**Comment by ArtPoon** [comment]
Second point is a duplicate of #217
