### ISSUE TITLE
Published version of a PipelineFamily should be invisible to users who don't have access to that version

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#401]
At the moment, the API and the PipelineFamily page will tell you what the published version of a PipelineFamily is regardless of whether you have permission on that version.  Restrict this so that if you don't have permission on the published version, you just see "None".

**Comment by rhliang** [comment]
Note: if a PipelineFamily has no revisions viewable to you, you shouldn't see it at all on this page.

**Comment by donkirkby** [comment]
Doesn't issue #407 make this issue irrelevant?

**Comment by rhliang** [comment]
I think a proper fix for #407 would also address this, that's true, but I think we left it open in case someone got to this before we did #407.  I might have a go at #407 right now though, or at least start it, so I'll use this as a reminder to not forget the security aspect.
