### ISSUE TITLE
Publish/unpublish buttons on PipelineFamily page don't work if you aren't the creator of the PipelineFamily

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#404]
Using the labupdatedemo fixture, as the `kive` user I'm able to modify the published version of the MiSeq pipeline without trouble, but as another user (belonging to the Developer) group, I was unable to use the buttons to do the same, even though the MiSeq PipelineFamily allows everyone access.

Two error responses are elicited from the server.  One is a 403 error saying that you don't have permission.  The other is a `301 Moved Permanently`, which is somewhat baffling.

In the meantime James put in a little bit of error handling and reporting so the page will display an error when this happens.

**Comment by rhliang** [comment]
Quoth Josh: the 301 Moved Permanently is because of a missing slash at the end of a AJAX call URL.

**Comment by ArtPoon** [comment]
Not relevant if we fix #407
