### ISSUE TITLE
Show file sizes in more appropriate units

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#405]
At the moment, file sizes of Datasets are shown in bytes.  Now that we're running on the cluster, we're starting to see more *real* data, with file sizes sometimes in the gigabyte range.  Let's make the Datasets page report our files back in more readable units.

**Comment by donkirkby** [comment]
The pipeline results page shows file sizes in different units, so check how it does it. I think there might be a helper in `permissions.js`.
