### ISSUE TITLE
Cannot upload files with unusual characters as CodeResources

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#406]
Building on #403, the code that handles creation of new CodeResources sets `filename` to the name of the file that has just been uploaded.  That's why we run into problems: the `filename` field of CodeResource must obey the regular expression `^(\b|([-_.()\w]+ *)*[-_.()\w]+)$`.  Some options for a way forward:

* continue to only allow users to upload files that are named appropriately on their computers, and instruct them of this requirement
* allow users to upload any file, but allow them to specify an alternate filename that obeys the regex
* loosen the regex so that we just accept more filenames

One idea that I think *won't* work is to slugify the filenames ourselves.  Developers that use this CodeResource may rely on the CodeResource filename being known exactly, as it's used when "installing" the CodeResourceRevision into a sandbox.

Also, whatever check we end up doing should be carried out by the frontend.  As it is, the error is only reported to you *after* uploading your file, which might be slow.

**Comment by rhliang** [comment]
As of commit 99eaef29d3493b74877ceca6a7eed1c76ac80791, the frontend will now at least tell you that the filename is bad.

**Comment by ArtPoon** [comment]
It is ok to leave this at rejecting the file, notifying the user that the file was not uploaded because of its filename, and to provide some guidelines to what a valid filename is.

**Comment by rhliang** [comment]
We changed the error message to be more explicit, describing exactly which characters can be used in the filename.
