### ISSUE TITLE
Change publishing to pre-release flag

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#407]
Art and I were talking about a different approach to the pipeline development workflow: make a pre-release checkbox on each pipeline instead of choosing one to be the published version. When displaying the pipeline families on the analysis page, choose the latest pipeline in a family that is not marked pre-release, and use it as the default.

The current approach means that one developer's changes can affect other users in surprising ways when different users have been granted access to different pipelines in the family. It's causing problems like issues #401 and #404.

**Comment by rhliang** [comment]
Current plan of attack: regular users should only be able to select from published versions of pipelines when starting analyses.  Developers/admins can select any.  If there's only one published version of a pipeline, the regular user doesn't get to choose at all -- the usable version is displayed in static text.
