### ISSUE TITLE
Retrieving pipeline from data md5 provides no information about inputs

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#411]
The user should be able to check which raw inputs were used in the pipeline.  This came up for me when I was processing a set of inputs with the same pipeline.  The pipeline output files have generic names, and I have no straightforward way of determining which output is linked with which input, short of relabelling the pipeline outputs once I retrieve each one from the run list (which fortunately does mention one of the pipeline inputs).

**Comment by jjh13** [comment]
When looking at runs, the user can now view the dataset by right clicking on the input. Additionally, the lookup functionality will check for runs where a dataset was used as an input.

Does this close the issue, or was something more needed?

**Comment by rhliang** [comment]
Does this also add appropriate entries to the View Results page?  If so, then I think this closes the issue.

**Comment by jjh13** [comment]
No, but that can (probably) be easily added.
