### ISSUE TITLE
Change Name of Results File Prior to Download

### ISSUE THREAD

**Issue by greenbeard1** [cfe-lab/Kive#412]
One suggestion would be to have a box popup allowing one to change the name of the results file to something informative to the user prior to the download. 

Of course one can change the name of the file after the fact or even using save as but it would be better to have a file save popup box when one clicks on the download button.

**Comment by ArtPoon** [comment]
It might be nice to select from small number of suggested templates to choose from.

For example:

[pipeline input filename] + [pipeline name] + [pipeline version] + [output name]

In the case of multiple pipeline inputs, the template would default to the "first".

**Comment by greenbeard1** [comment]
Yeah super good to have that version info in there. Let's say I also wanted
to add the word vidus or something to remind myself what the output was and
ideally save it to a custom folder rather than  downloads

**Comment by donkirkby** [comment]
I think there's a response header called something like disposition that will trigger the Save as... dialog with a default name.

**Comment by donkirkby** [comment]
Fixed in 710a1be1becd6e7eba568a4f45ea849343bf76d5. Closing the issue.
