### ISSUE TITLE
Clean up intermediate data after a run to save space

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#414]
Since we're already feeling a space crunch on the cluster, we should start thinking about a good policy for removing data "non-destructively" from a Run, and also perhaps compressing old data using gzip/bzip2/etc.

**Comment by ArtPoon** [comment]
We will want to implement data removal at three steps:

1. by pipeline definition (assembly) where the user specifies which steps to discard after processing
2. automated by Kive based on a rolling wall like limited disk space allocation or creation date threshold.
3. manually triggered by user.

See issue #413.

**Comment by donkirkby** [comment]
Might also need to consider purging data check records, since there can be many failures in a single file.

If we've purged an output dataset, user should be able to request a rerun of that file. It would also be nice to see when it's already been rerun.

**Comment by ArtPoon** [comment]
Closing.  Mostly covered by #413.
