### ISSUE TITLE
Duplicate dataset was allowed to be uploaded

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#417]
Jeff was uploading a dataset when his browser hung, so he started the upload again.  We ended up with two of the same file, with the same filename:

![duplicate datasets](https://cloud.githubusercontent.com/assets/5862525/9912317/bbc83e80-5c5b-11e5-977d-21fb11d588df.png)

I confirmed that the two files were identical.  I removed the duplicate before I thought to investigate further on the shell.  Possibly this was due to a race condition?

**Comment by rhliang** [comment]
I just tried this myself and was able to upload the same file twice without it complaining.  I'm guessing that the validation step that checks for duplicates based on MD5 and Dataset name is not being called on the frontend (it may be in `clean`).

**Comment by ArtPoon** [comment]
I've implemented a check for this in archive/views.py:datasets_add() in the `kive_api` branch.  
Will merge over to master with close of this branch.
