### ISSUE TITLE
Pointers to external filesystems to retrieve raw inputs

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#423]
Kive should not have to store raw inputs indefinitely - this is the role of the lab's data archival system.  However, if a raw input has been deleted from the Kive filesystem, we should be able to automatically retrieve that file from a number of trusted sources.  The external folder(s) are the system of record.

* [x] ~~define external folders in `settings.py`~~
* [x] define external folders in a database table
* [x] implement management commands for adding to ~~or modifying entries in~~ this table
* [x] instead of uploading a dataset, retrieve it from an external folder
* [x] when you re-run a pipeline and we do not have an internal copy of the input, then retrieve it from the external folders
* [x] ~~store the original path at upload (use Django's filepath field)~~
* [x] store the original path at upload using CharField (FilePathField is too limiting).  This path is relative to the specified external file directory
* [x] ~~have Kive routinely scan for the presence of external data sets and notify users when one is missing~~ (EDIT 2016-03-31: this functionality can wait until a subsequent release, i.e. when we start changing the Manager to handle priorities)
* [x] give user the option to leave the data set as an external resource (not to be stored internally in the Kive framework) on upload
* [x] amend the removal and redaction routines for Datasets to reflect these changes and report any externally-backed Datasets that will be affected (e.g. warning the user that the external files will not be removed/redacted)
* [x] update Datasets page to not offer downloads of Datasets that have missing data (extends to data that has been purged or redacted as well)
* [x] ~~similarly, update View Results page to not offer downloads of Datasets that have missing data~~ (EDIT 2016-03-31: this already existed)
* [x] ~~similarly, update View Runs page to not offer downloads of Datasets that have missing data~~ (EDIT 2016-03-31: turns out there are no download links at all anyway

Consider using this [simple filesystem browser][fs] or a [more sophisticated browser][dfb].

[fs]: http://rfc1437.de/page/writing-a-simple-filesystem-browser-with-django/
[dfb]: https://github.com/sehmaschine/django-filebrowser

**Comment by rhliang** [comment]
With the heavier load we're seeing right now, this has to be bumped up the priority.  Aim to address this for a v0.7.2 release.

**Comment by ArtPoon** [comment]
For the time being, restrict `kive` and `apache` users to read-only access to external file system for purpose of development and validation.  In the future, we would like to enable write permissions so that outputs can be distributed to external file systems as well, but read-only should be adequate for this specific issue.
