### ISSUE TITLE
Allow user to configure how datasets are purged

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#424]
Merge `outputs to delete` branch into master, at pipeline assembly step.

**Comment by donkirkby** [comment]
Not sure if this is complete or not. I think you were working on it, @jnak-cfe, so please close it if it's complete. If it's waiting for someone else, please add a note.

**Comment by jnak-cfe** [comment]
Complete as of 3a11bf453840ab321f7f52e30b61597f3a8823e4.
