### ISSUE TITLE
Clicking on banner during pipeline assembly causes loss of all work

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#427]
This is a really frustrating event if you accidentally click anywhere on the upper region of the page (i.e., the banner that contains the Kive logo).  This immediately takes your browser to the portals page.  Any objects that were placed on the HTML5 canvas are immediately lost.  Can we limit the active area of the banner to the logo only?

**Comment by jnak-cfe** [comment]
Probably the best solution would be to confirm with the user that they intend to leave the page via the beforeunload event. (Only on this page and other pages where a significant amount of work is done by the user.)

**Comment by jnak-cfe** [comment]
Just fixed this the way that I would want to fix it—feel free to re-open if shortcomings with this approach.
