### ISSUE TITLE
Make it easier to update a CR that depends on a recently changed CR?

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#428]
I had to fix a bug in a code resource (CR) that is a Python module dependency for another CR.  All that I want to do is point the second CR to the newer version.  In order to do this, I need to go through the entire revision workflow, which includes uploading the file.  However, what if I had local changes in this script that I didn't want to commit to Kive?  What if I can't find the original file on my workstation?  

I think that it should be possible for the user to ask Kive to carry over the file from the previous CR when submitting a revision.  We could even make this the default value in the file field.  Any thoughts?

**Comment by rhliang** [comment]
I believe this is already on the docket: does #374 cover this?

**Comment by donkirkby** [comment]
Closing as duplicate.
