### ISSUE TITLE
Published button on Pipelines page wraps awkwardly

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#429]
Ran into this just now:

![publishedwrap](https://cloud.githubusercontent.com/assets/5862525/10228737/4052d4fc-6829-11e5-8912-544fce7ffdee.png)

**Comment by jnak-cfe** [comment]
Did this happen when you shrank the browser window or was it the table's content that made it wrap?

**Comment by rhliang** [comment]
It was the table's content, but it also happens when you shrink the window.  If you widen the window it goes back to the way it should.
