### ISSUE TITLE
stderr not being reported to console

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#431]
The default MiSeq pipeline that is distributed in the Kive `demo` fails on Art's workstation, possibly  because of a version conflict in Ruby when loading `alignment.bundle`:
```
1: sam_g2p.sh stderr
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Volumes/Crawlspace/media/Sandboxes/userkive_run1_VD7U3D/step5/alignment.bundle, 9): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE (LoadError)

  Referenced from: /Volumes/Crawlspace/media/Sandboxes/userkive_run1_VD7U3D/step5/alignment.bundle
```
This information only appeared because Art inserted some print statements into Kive `method/models.py` in the Method class function `_poll_stream`.  This should probably be made more visible.

Migrated this issue from cfe-lab/py-kive-api#3.

**Comment by donkirkby** [comment]
@ArtPoon, can you clarify whether this error shows up in the stderr for the run step? Does the fleet crash?

**Comment by ArtPoon** [comment]
This is not a Kive issue, it is py-kive-api.
When I run the same pipeline and data sets using the Kive GUI, the `sam_g2p.sh` step lights up red as it should, and I can find the stderr log.  
When I run this under py-kive-api, I get the following:

```
Hypnotoad:py-kive-api art$ python example.py
('@api_auth', {'username': 'kive', 'password': '****'})
[redacted csrf token]
OK
1:  - rev 1
('@api_runs', {'pipeline': 13, 'input_2': 3, 'csrfmiddlewaretoken': ****', 'input_1': 2})
Running...
*:....-............... 4.7619047619 %
Running...
***...-**..*...*...... 33.3333333333 %
Running...
****::-***.**..*...... 47.619047619 %
Run failed!
****!*-*******.*.*.*** 80.9523809524 %
Finished Run, nabbing files
```

I wrote the issue because from the API perspective, the user would not be immediately aware of a run failure unless they checked `run.is_successful()`.

**Comment by ArtPoon** [comment]
Also, the fleet does not crash now that I am decoding log messages to Unicode.

**Comment by donkirkby** [comment]
Sorry, I misunderstood where the problem is. Migrating back to cfe-lab/py-kive-api#3.
