### ISSUE TITLE
Abbreviated list of CompoundDatatypes can mask differences

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#432]
Currently we are displaying truncated string representations of CompoundDatatypes in the dropdown options menu (for example, when defining a Method's inputs and outputs).  It is possible for two CompoundDatatypes to have the same truncated representation. 

Possible resolutions:
- activated drop-down gives full string descriptions of CDTs
- hover over option gives full string description as tool tip
- others?

**Comment by donkirkby** [comment]
We've also talked about giving compound datatypes a name and description, like other developer objects.
