### ISSUE TITLE
Smarter dataset purge

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#434]
We used a very simple strategy for issue #413: delete the oldest datasets until the disk usage goes below the lower limit.
- [x] ~~Break up purge over multiple polling cycles to avoid stopping the fleet for several hours.~~ It only takes a few minutes, now.
- [x] See if there are smarter ways to store the dataset files. Look at [pytables](http://www.pytables.org/), for example.
- [x] Think about other criteria to use for choosing which datasets to purge: size, age, age of run inputs, access patterns, or time needed to regenerate. Choose the most relevant criteria, and design a weighted score to rank datasets.
- [x] Purge datasets ordered by that score.
- [ ] If more than half of the datasets don't match the database, don't delete anything and shut down the fleet. You're probably pointing at the wrong database or the wrong media root.
- [ ] Stop the fleet if you can't purge below the upper limit.
- [ ] On the run results page (table of outputs), distinguish between purged outputs and outputs that weren't retained.
- [x] On the run results page, add a rerun button to recreate purged outputs.
- [ ] On the view results page (pipeline diagram), show discarded data somehow. Maybe the same as the black magnet that shows deleted intermediate datasets, or perhaps a different colour for the cables.
- [x] Purge log files. On 17 Jun 2016, there were about 850000 log files taking up almost 700M of disk space.
- [ ] Make all empty data sets and log files point to the same empty file: `/data/kive/empty_file`. It just reduces clutter in the file system.
- [ ] Combine storage limits for sandboxes, datasets, and log files. Purge them together.
- [ ] Consider two levels of purge: compression and deletion.
- [x] Don't purge a result if the run batch is still active.

If any of these items are too large to include in this issue, split them into separate issues.

**Comment by wrpscott** [comment]
Can purge data according to a score calculated from access time and file size. Evaluated the metric on a production dataset (without actually purging).

**Comment by rhliang** [comment]
Will also address #481 alongside this.

**Comment by wrpscott** [comment]
Now purge datasets and log files according to a time and size metric. This version uses the scandir module 59fce42 closes this for now.
Note that #549 is not in this commit.
