### ISSUE TITLE
We should allow users to upload an empty file as a CR

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#440]
Right now I am trying to create an `__init__.py` CodeResource so that we can have relative imports within a Python package that is going under Kive control (Micall pipeline v7.0).  However, Kive does not allow users to submit an empty file.  This is a counter-productive restriction.

**Comment by rhliang** [comment]
Problem was that we need to explicitly set `allow_empty_file=True` in `CodeResourceRevisionForm` and `CodeResourcePrototypeForm`.  The backend was allowing this already.
