### ISSUE TITLE
Avoid stale Javascript in browser cache

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#442]
Browsers often cache the Javascript files, so changes are not visible until you force a refresh.

Steps to reproduce:
1. Go to a web page that links to a Javascript file.
2. Make an obvious change to that Javascript, like adding an `alert('changed!');` to the page start up script.
3. Navigate your browser away to another page, and then navigate back to the changed page. (Don't use your back button or refresh the page.)

Expected behaviour: the change should be visible. For example, an alert box should show.

Actual behaviour: varies depending on the browser cache behaviour, but at least sometimes the change is not visible.

Workaround: force the browser to refresh, usually with a key combination like Ctrl-F5 or Ctrl-Shift-R.

The most common fix I've seen suggested is to add a query parameter to the script link and update that parameter when the Javascript changes. It's simple, but requires a manual update for every change.

Another option is to automatically add a query parameter that is a hash of the file contents. It sounds like Django's `static` template might [do that automatically](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#std:templatetag-staticfiles-static), as described in [this blog post](https://mike.tig.as/blog/2011/12/22/django-14-first-thoughts-cachedstaticfilesstorage/). If not, there's a package called [django-compressor](https://github.com/django-compressor/django-compressor).

Finally, there's a [grunt task](https://www.npmjs.com/package/grunt-django-static-hash-append) that works during deployment.

**Comment by rhliang** [comment]
Try the [CachedStaticFilesStorage option][cf].

[cf]: https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.CachedStaticFilesStorage

**Comment by nathanielknight** [comment]
`CachedStaticFileStorage` is [deprecated since version 2.2](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#cachedstaticfilesstorage). The docs recommend [`ManifestStaticFileStorage`](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) instead.
