### ISSUE TITLE
Run status display is wrong

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#450]
The list of runs isn't displaying the run steps correctly. As soon as the run starts, they all become colons. They should be periods while they wait for their inputs. The run outputs are displayed correctly.

**Comment by rhliang** [comment]
As part of the fixes for issue #413, the execution algorithm now performs multiple passes over the Pipeline before it executes things.  The first pass creates RunSteps for all steps, which it didn't before.  The criteria for whether a RunStep is "READY" or not, according to the `get_run_status` method on RunToProcess, is that a RunStep exists but no ExecLog exists.

To remedy this, we refine our interpretation: a RunStep that exists without having its `start_time` set is one that has been passed over but is not ready to go yet.  We change the criteria for "readiness" to be that a RunStep that exists but has not been started yet.
