### ISSUE TITLE
Add a filter from page 2

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#466]
Steps to reproduce:

1. Go to any search page with more than one page of results.
2. Click next.
3. Add a search filter that will match fewer than 25 results.

Expected behaviour: displays the newly filtered results.

Actual behaviour: displays an error message, 'Invalid page "2": That page contains no results.' Clicking the previous link takes you to the results page.

We just need to go back to page 1 whenever we add a search filter.

**Comment by rhliang** [comment]
Yep my bad, I'm on it.
