### ISSUE TITLE
Feedback to indicate that a pipeline step has been updated

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#468]
Append an asterisk to method name on the pipeline assembly canvas to indicate that it has been changed.  Also disable navigation warning when leaving page if there are no changes to pipeline.

**Comment by jnak-cfe** [comment]
Partially addressed in c0b00d00e0734772d8346a1ca64aef3ebb7112ec

**Comment by jnak-cfe** [comment]
Question about this:
Should this flag be switched on only when methods are *updated*? or should new (unsaved) methods and inputs/outputs have an asterisk appended to them as well?

**Comment by donkirkby** [comment]
My vote is that an asterisk appears on any node with an unsaved change. A new node has not been saved, so it should have an asterisk.

**Comment by rhliang** [comment]
Good point, and I'll vote with Don as well.  Would this extend to a Pipeline that we're assembling for the first time, for consistency?

**Comment by donkirkby** [comment]
I think it would, @rhliang. Make it simple and consistent. If all the nodes on a new pipeline will be marked, it should probably be a pretty small indicator.
