### ISSUE TITLE
Check for updates doesn't set MD5

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#476]
When you click the Check for updates button on the pipeline page, it doesn't set the MD5 on new code resources. It has to make a new code resource if one of the dependencies has changed.

A helpful tool to check for bad MD5's is the `check_md5s` management command.

**Comment by ArtPoon** [comment]
For example, if a CR's dependency has changed, then the parent is a new CR even though its file content has not changed.  However, the md5 checksum field is not being transferred to the new CR.

**Comment by ArtPoon** [comment]
This should be resolved by #519

**Comment by ArtPoon** [comment]
This may be obsolete, check.

**Comment by donkirkby** [comment]
Resolved by #519.
