### ISSUE TITLE
Should we try and identify whether a Dataset is binary (for viewing purposes)?

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#478]
While working on #217, I've noticed that when you view a raw text Dataset, it appears like:

![rawtext](https://cloud.githubusercontent.com/assets/5862525/11510315/0bd60482-9818-11e5-8494-1e32367784c5.png)

But when you view a raw binary Dataset, it appears like:

![rawbinary](https://cloud.githubusercontent.com/assets/5862525/11510326/14d0a092-9818-11e5-8940-36499fb8a06c.png)

Should we make an effort (e.g. using [python-magic](https://github.com/ahupp/python-magic), or by parsing a bit ourselves to spot non-text characters) to guess whether a file is binary or not so we can put a message like "This is a binary file" on this page?

**Comment by ArtPoon** [comment]
We discussed this at a meeting and decided to proceed with automatically detecting whether the file is binary and then displaying a warning message ("This is a binary file") without displaying any file contents - but including a link to download the file.

**Comment by rhliang** [comment]
I actually (thought I) fixed this, and thought that I had closed this issue.  Closing now because issue #567 is the evolved form of this issue.
