### ISSUE TITLE
Discuss: add link from ExecRecord to the top-level Run that generated it

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#482]
I'm finding that doing the lookup of the generating Run of an ExecRecord is unpleasantly slow when checking for permissions on these generating Runs.  Maybe it's worth replacing the `generating_run` property with an actual field, that keeps track of this.

**Comment by ArtPoon** [comment]
Don's profiling determined that it was the unnecessary multiple checking of objects that was the main culprit of slow performance, not this.  Closing as this does not currently represent an issue.
