### ISSUE TITLE
Kive not compatible with Django 1.9

### ISSUE THREAD

**Issue by jnak-cfe** [cfe-lab/Kive#483]
I tried doing a fresh install today, and I got as far as installing all the dependencies and setting the database up.

When I ran `./manage.py migrate` for the first time, I got this:

```
  File "/Users/james/git/Kive/kive/datachecking/models.py", line 10, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic
```

A few Googles later... [Django 1.9 release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/)
```
The django.contrib.contenttypes.generic module is removed.
```

**Comment by rhliang** [comment]
Just made a change that should fix this.  @jnak-cfe when you have a chance can you check and see if this addresses the issue?

**Comment by jnak-cfe** [comment]
It did indeed, however another one has been removed:

```
  File "/Library/Python/2.7/site-packages/rest_framework/request.py", line 17, in <module>
    from django.utils.datastructures import MergeDict as DjangoMergeDict
ImportError: cannot import name MergeDict
```

**Comment by rhliang** [comment]
Ah, that looks like it's coming from Django Rest Framework, not us.  What version of DRF are you using?  Seeing as Django 1.9 came out on December 1, we may just have to hope that Django Rest Framework heeded the deprecation warning....

**Comment by rhliang** [comment]
According to their Github, this was fixed in DRF v3.1.1, so we should be good there (until we find the next thing).

**Comment by jnak-cfe** [comment]
Thanks, I don't know why I didn't have a current DRF, since I installed it from pip today...
I think we're *almost* at the bottom of this.

**Comment by jnak-cfe** [comment]
This is what I've run into now. looks kind of hairy

```
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
```

**Comment by rhliang** [comment]
For reference, here are things that did not work:

* running `./manage.py migrate auth` before running `migrate` (as per http://stackoverflow.com/questions/29689365/auth-user-error-with-django-1-8-and-syncdb-migrate)
* running `./manage.py makemigrations` as per http://amfarrell.com/random-notes/ -- this fails with the same error
* dropping and recreating the database

Things we should maybe try:

* creating explicit migrations for third-party apps as per https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies
