### ISSUE TITLE
Running code using SSH is broken on the cluster

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#489]
We're still getting the error

```
ssh_exchange_identification: Connection closed by remote host
```

as we were in #486, so the fingerprints were not the issue.  Things we've tried:

* setting up SSH fingerprints on all child nodes
* checking for a limit on number of SSH logins

Things to try:

* look at `hosts.allow` and `hosts.deny` on the child nodes
* look for permissions issues
* it's also possible that we're just overwhelming the server we're logging into (see http://stackoverflow.com/a/15822474/4216388)
* adjust `MaxStartups` in `/etc/ssh/sshd_config`.  Someone on stackexchange said that this is not set by default on CentOS 6.4, but according to other sources (including the cluster's man page), the default is 10.  This seems like a likely culprit.  Note that if this is the case we'll also have to change `sshd_config` for the child nodes.

**Comment by rhliang** [comment]
Issue appears to be the limit on `MaxStartups` in sshd.  We could probably address this by increasing that number, but we think a system that retries on a bad connection makes more sense.  For now, we'll convert the cluster back to regular execution not using SSH.

**Comment by donkirkby** [comment]
Here's a simple test script that exposes the problem when you run it under the `kivefleet` user.

```
from argparse import ArgumentParser
from collections import Counter
from multiprocessing import Pool
from subprocess import check_output, CalledProcessError
from time import sleep


def run_task(i):
    try:
        # sleep(0.01 * i)
        return check_output(['ssh', 'kivesandbox@localhost', 'whoami'])
    except CalledProcessError as e:
        return 'return code {}'.format(e.returncode)


def main():
    parser = ArgumentParser()
    parser.add_argument('worker_count', type=int)
    args = parser.parse_args()

    pool = Pool(args.worker_count)
    counts = Counter()
    for result in pool.imap_unordered(run_task, range(args.worker_count)):
        counts[result] += 1
    for result, count in counts.iteritems():
        print result.strip(), count

main()
```

If I run it with 30 processes, 10 succeed, and 20 fail. If I add a different delay before each call to ssh, then they all succeed. They continue to succeed if I add a delay during the ssh call, so I think the limit is on how many sessions are trying to log in at the same time, not how many sessions are open.

**Comment by donkirkby** [comment]
Suggested fix: add a random sleep and retry when the ssh fails. It's a bit tricky to see when the ssh has failed. We could check for the return code 255 and some of the error message, or we could change the sandbox execution to something like this:

    ssh kivesandbox@localhost 'touch sandbox1234/step1/launched.txt && step1.py arg1 arg2'

That way, the first thing it does after ssh is to touch a file. If we don't see that file, then we know the ssh failed and we retry. Not sure if this is any better than checking for a specific error message in the output.
