### ISSUE TITLE
apache creates files in the Sandboxes directory that cannot be reaped by kivefleet on the cluster

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#490]
#At the moment, we are trying to use the `kivefleet` worker to run the fleet, but not use SSH for execution (i.e. not using `kivesandbox` to execute the sandboxes).  Under this scheme, `kivefleet` will run the sandboxes instead of `apache`.  The problem is that, as mentioned in #475, when a dataset is uploaded, `create_dataset` still creates a subdirectory in the sandboxes directory, and because `KIVE_SANDBOX_WORKER_ACCOUNT` is not set in the settings, `file_access_utils.configure_sandbox_permissions` does not modify the permissions on this new subdirectory to be accessible by `kivefleet`.

For now we can work around this by changing `apache`'s default umask so that the files and directories it creates are accessible by the group.  Moving forward, we will have to choose a course of action.

* [x] address #475, which would sidestep this specific problem
* [x] write a helper that will recursively alter the subdirectory's permissions and those of its contents so that they're accessible by `kivefleet`

Whichever way we go, we must also:

* [x] ~~reset `apache`'s default umask~~

**Comment by ArtPoon** [comment]
This issue also affects DataSets, see #484

**Comment by rhliang** [comment]
Having changed our approach to #475 and closing it, we can consider this issue mostly resolved.  Note that the second bullet point ("write a helper...") is how we addressed #475, so I ticked both boxes.  We can close this issue when we reset `apache`'s umask.

**Comment by rhliang** [comment]
It appears that apache's umask was actually not changed to anything unusual, or at least I can't find the relevant setting in `/etc/httpd/conf/httpd.conf`.  Moreover, when I use `sudo su -s /bin/bash apache` to run a shell as apache, the `umask` command gives me the umask that we actually want.  Closing this issue.
