### ISSUE TITLE
Speed up fleet by adding state fields

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#493]
We made several performance improvements to the fleet in issue #491, but it's still pretty slow to advance a pipeline. One of the big costs is repeated calls to methods like `is_complete()`, `clean()`, and `is_successful()`. All of these methods involve walking through a bunch of records in the librarian and archive modules to see what happened to a run, its run steps, and all the cables.

Adding state fields on the run and run steps, and possibly on the cables could eliminate a lot of these look ups. Do all of the look ups once when the state is transitioning, then trust the state fields when advancing the pipeline.

**Comment by rhliang** [comment]
There are also calls to `is_complete()` and `is_successful()`, along with `is_redacted()`, in the `save()` method of `RunComponent`.  It may be worth examining this as well later.

**Comment by rhliang** [comment]
Note that there are fields named `_complete`, `_successful`, and `_redacted` on `RunComponent` already, they're just not being used during execution.  We can just add analogous fields to `Run`, change a few calls to `is_complete()` and friends, and Bob's your (our?) uncle.

**Comment by rhliang** [comment]
Speaking of, this may be an opportune time to discuss the names of these variables.  They were defined with underscores to emphasize that they're meant to not be accessed by the user, but I'm getting the impression this was not a well-liked choice.  Thoughts?

**Comment by ArtPoon** [comment]
We discussed the underscore issue and we are fine with it.

**Comment by donkirkby** [comment]
I think there's a bug in this fix. I ran a bunch of runs last night, and some of them finished all the steps, but never got the `run.end_time` set. Now, any run I start finishes all the steps, but leaves `run.end_time` null.

**Comment by rhliang** [comment]
Forgot to mention that we found the bug that was causing `run.end_time` to not get set.

I finally got some other issues closed so can now look at adding some tests for this functionality.  Some of it will be folded into tests we already have, I think.
