### ISSUE TITLE
Limit data display for raw data sets

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#497]
Currently if a user attempts to view a raw data set, the browser will attempt to render the entire contents of the file.  This can be prohibitively large such as the case for a FASTQ file.  Start with a limit of 100 lines, and provide a link for downloading the entire file.

**Comment by ArtPoon** [comment]
Related to #478

**Comment by donkirkby** [comment]
This was fixed a while ago. Closing the issue.
