### ISSUE TITLE
Let user add new methods in pipeline assembly page

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#504]
Acknowledging that pipeline creation is broken, usability-wise, a logical first-step would be to add a method creation dialog to the pipeline assembly page. This can be done without any significant back-end changes.
#505 advances this flexibility with back-end enhancements.

**Comment by jamesnakagawa** [comment]
This is proving quite difficult to conceptualize. We may need to find ways to simplify.

Considerations:

* Method may be based on an existing **or** new CodeResource.
* Method may be part of an existing **or** new MethodFamily.
* Method may have CodeResource dependencies.

Questions:

* Is _new_ CodeResource or _existing_ the more common use case?
* Same question about MethodFamily (I am thinking the answer would be "new", though)
* If new CodeResource, can we think of a way to generated the name/desc on the Method's name/desc?
* Same question about MethodFamily

**Comment by donkirkby** [comment]
I think updates happen more often, but creating new items will be more common for new developers, because I expect the first thing a new developer will do is try to add a new pipeline. If we can only improve one of these scenarios, I think the new developer is more important, because we have to persuade them that the tool is useful.

How about this for a simplifying assumption? If creating these items on the pipeline assembly page is impractical, we could store the work in progress somewhere and make it easy to move between the pipeline assembly page and the item creation pages.

Storage possibilities:

* browser local storage
* browser session storage
* database with relaxed restrictions (this would also avoid the problem where another user launches a pipeline while the developer is working on it, because they couldn't launch the in-development pipeline)

**Comment by jamesnakagawa** [comment]
I think we have to keep some sort of breadcrumb or tie to the pipeline creation page, and not let the user forget that this is the "root" task they are committed to. Navigating away from the page might cause users to hesitate if they aren't sure that their work will be saved.

We could have a vertical tab-style interface allowing the user to switch between pipeline view, method view, CDT view, and CRR view. If we go this route, we will have to think about browser history since the user will now expect the back button to take them to the previous tab they had clicked. However, this will still all happen on one page. I'll also say that this may not simplify things as much as I would like -- the less "optional" fields we make the user consider, the better, I think.

Example: (forgive the crudeness of the diagram!)
![nav-sidebar](https://cloud.githubusercontent.com/assets/6126553/19817191/5bb779e4-9cff-11e6-8df8-aa9774e3c865.png)

The other option is to go with a type of modal panel.

Since we will almost certainly need more space for this form, a sidebar will anchor the content much better than a floating dialog. We could list all the form controls vertically, or maybe section it into an [accordion-type widget](https://en.wikipedia.org/wiki/Accordion_(GUI)). The sidebar would disallow interaction with the canvas while it is active.

Example:
![method-sidebar](https://cloud.githubusercontent.com/assets/6126553/19817192/5bcdbda8-9cff-11e6-9818-11270ce55483.png)

I still think this asks for a lot of information that we don't necessarily need - if we can provide default values for any of these fields, and then collapse them into an accordion as mentioned, I think it would go a long way towards our goal of simplifying the interface.

**Comment by donkirkby** [comment]
How about an alternative workflow for creating pipelines in a pipeline wizard, kind of like the installation of an operating system. It might go something like this:

* welcome
* choose example inputs (preferably small)
  * either select an existing dataset or upload a new one
  * detect compound datatype of new dataset
* add step
  * choose existing method or add new one
  * choose existing version of method or upload new code resource revision
  * choose inputs from examples or previous step outputs
  * add and name outputs
  * run
  * detect compound datatype of outputs
* add more steps
* select pipeline outputs
* publish

Is that appealing? Is it too crazy?

**Comment by jamesnakagawa** [comment]
My concerns with this approach (and wizards in general) are that it may create a redundant workflow, and that it's _too_ linear (may not afford the flexibility we currently have in the interface).

There could be smaller chunks that we could turn into a step-by-step "wizard", like with the method sidebar I proposed. I'm not terribly opposed to doing that if there's a need to section the content.

Am I right in assuming that adding a method is the first intuitive step in pipeline creation?

I think if we ask the user to choose between "Full Pipeline Creation Interface" and "Pipeline Creation Wizard", it's a bit like a sandwich maker asking you if you want regular mayo or the special sauce. I might prefer one over the other, but I have no idea which until I've tried both.

**Comment by jamesnakagawa** [comment]
Trying to build on previous ideas — here's yet another idea:

* Ask the user to add a "first step" to their blank pipeline canvas.
* Guide them through either choosing an existing method or creating a new one.
* Assume that the inputs to this method will be inputs to the pipeline
* Select the method and present these contextual controls:

![first-step-ux](https://cloud.githubusercontent.com/assets/6126553/19821978/0df733e0-9d16-11e6-92ec-d64815174e3b.png)

* These contextual controls could be displayed next to the node, or in a top toolbar just below the global menu.
* "Finish Pipeline" will just create outputs from all out-magnets.
* "Next Step" will guide them through the same process as above, and filter existing methods by ones that have at least 1 input in common with the first step's outputs.
* Repeat

**Comment by jamesnakagawa** [comment]
Despite my earlier concerns, we (@rhliang and I) like @donkirkby's idea to stash unfinished pipelines in some sort of storage, with the addition that a thumbnail of the pipeline canvas should be present when one is stored. This thumbnail should link back to the pipeline creation page.

When creating a new MethodFamily (which is the primary goal for this interface), we should be able to generate names/descriptions/permissions for the revision name/description/permissions and CodeResourceRevision name/description/permissions as a convenience for the user. The user could still customize these if desired.

This is to facilitate the user leaving the pipeline creation page to create new methods and CDTs. We would also want to beef up the method creation interface so that all CRRs (driver/dependencies) and CDTs could be created on the fly.

We also discussed possibly improving the terminology:

* "Method Families" may be better explained as "Methods"
* "Methods" may better be explained as "Method Versions"
* Same goes for pipelines/pipeline families

**Comment by donkirkby** [comment]
Sounds good. Can we be consistent with "versions" or "revisions"? I'm fine with versions, but we should then change "code resource revisions" to "code resource versions".

**Comment by jamesnakagawa** [comment]
Yes, good point. I like "versions" better because it seems clearer what it is. Hopefully it's not too onerous to change.

**Comment by rhliang** [comment]
A bit of a pain, but shortly after having released 0.8 is the right time to do something like that.  It shouldn't be difficult but it requires a database migration.  A relatively trivial one, but any database change is a potentially difficult one.

**Comment by rhliang** [comment]
Don and James will look at the differences in format between what the back end accepts and what it returns.
