### ISSUE TITLE
Make pipeline creation more flexible for improved usability

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#505]
This issue is inter-related to #506 and #504.
- [ ] Methods should allow null CRRs
- [ ] CRRs should allow null dependencies
- [ ] Method inputs/outputs should allow null CDTs
- [ ] Pipelines should allow null CDT nodes
- [ ] Pipelines should check for completeness (no null values as given above) before being published or run
- [ ] Pipelines should that have not been run or published should allow edits _without_ auto-creating a new revision

**Comment by ArtPoon** [comment]
* currently the framework for adding a new pipeline requires a user to begin by specifying low-level objects (e.g., compound data types), which is counter intuitive
* the new approach would be to have everything take place in (or around) the pipeline assembly page, and use "swipe down" or "modal" dialogs to present object-specific forms as the user is assembling the pipeline.
