### ISSUE TITLE
Make Run name stand out more on view_runs page

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#509]
Suggestions:

 - make the name bold
 - make the name larger
 - colour the text

**Comment by greenbeard1** [comment]
[NameHighlightIssue.pdf](https://github.com/cfe-lab/Kive/files/118075/NameHighlightIssue.pdf)

**Comment by greenbeard1** [comment]
![namehighlightissue](https://cloud.githubusercontent.com/assets/5864292/12826679/108c0e94-cb31-11e5-9899-86472e51564e.jpg)
