### ISSUE TITLE
Make user search results of run results persistant, perhaps using cookies.

### ISSUE THREAD

**Issue by greenbeard1** [cfe-lab/Kive#510]
If working with a series of runs, it is helpful to be able to download the results of one run, then hit the back button and be able to have the other runs you are working with still on the screen so that searching on your username is not necessary each time.

This could be accomplished using browser cookies?

**Comment by donkirkby** [comment]
Workaround for now: open the results page in a new tab, so you don't lose your filters on the list of runs.

**Comment by jnak-cfe** [comment]
I recommend using the [HTML5 history API ](https://developer.mozilla.org/en-US/docs/Web/API/History_API) to preserve the page state in browser history. Browser support for this feature is not bad—more demanding than our "Basic Support" requirements but similar to our "Bulk Upload Feature" requirements. (Chrome 5 / FF4 / IE10 / Safari 5)

**Comment by donkirkby** [comment]
I ended up using sessionStorage to hold the filters until the user closes the browser tab or window. I started out using history, but I think it's better to let the user browse around the run output pages, and still remember the filter settings when they navigate back to the runs page.

**Comment by donkirkby** [comment]
Reopening because @rhliang suggested storing the current page number with the search criteria.
