### ISSUE TITLE
Transition CodeResourceDependency to MethodDependency

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#519]
We've been talking about this one for a while: replacing the CodeResourceDependency class with MethodDependency.  As the name implies, this means that the code used for a Method is directly associated with the Method, rather than with its driver.  CodeResourceRevisions are now strictly single files, and there will be no "metapackage" CRRs that have no file attached.

I suggest we put this in v0.8, as getting it sorted out will make a fair amount of the new pipeline workflow more sensible.  I'm going to create a new branch to start working on this.

* [x] make MethodDependency and copy install/filepaths/circular dependence/clean code to Method, modify removal_plan
* [x] make a data migration to transfer CRDs to MDs (note: this is lossy and the reverse migration will be a noop)
* [x] convert demo fixtures
* [x] eliminate CRD and remove install/filepaths/circular dependence/clean code from CRR (comment it out for now), change forms/views/serializers/etc
* [x] disallow empty CRRs -- change clean of Method, CRR, CodeResource
* [x] take out commented code from CRR/CRD
* [x] look at the code around the Check for Updates functionality
* [x] fix tests

**Comment by donkirkby** [comment]
Another bug that this fixes: Check for Updates will create two code resource revisions that use the same `content_file` when it updates a dependency. Deleting one of those duplicate code resource revisions deletes the file, and the remaining code resource revision is broken.
