### ISSUE TITLE
Data migration failing to reset PostgreSQL primary key sequence

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#521]
After fixing #518, all the tests ran; however, after I did some other work on another branch, I found that if you run certain test cases that use the `testing_utils.create_metadata_test_environment` function, they will fail on `setUp`.  What appears to be happening is that they attempt to create Datatypes and CompoundDatatypes with primary keys starting at 1, even though several such Datatypes/CDTs were defined in the data migration.  I suspect this is probably because I explicitly set the primary key of the objects I defined in the data migration to make sure they were consistent with our existing `initial_data.json` fixture.

**Comment by donkirkby** [comment]
The Django management command `loaddata` [resets all the database sequences][reset] after it loads data from a file. We might need to do something similar in the data migration.

[reset]: https://github.com/django/django/blob/1.9.2/django/core/management/commands/loaddata.py#L114

**Comment by rhliang** [comment]
Yep and I believe that's why the problem wasn't found before.  When running the entire suite together, it probably ran another test case that successfully loaded fixtures or did the same kind of sequence reset before it got to the ones in `metadata.tests` that are giving me problems.

**Comment by rhliang** [comment]
I switched back to master and incorporated this code into the offending data migration (based on code from Django's `TransactionTestCase` class):

```
    conn = connections[DEFAULT_DB_ALIAS]
    if conn.features.supports_sequence_reset:
        sql_list = conn.ops.sequence_reset_sql(
            no_style(), [Datatype, BasicConstraint, CompoundDatatype, CompoundDatatypeMember])
        if sql_list:
            with transaction.atomic(using=DEFAULT_DB_ALIAS):
                cursor = conn.cursor()
                for sql in sql_list:
                    cursor.execute(sql)
```

and now the tests and migrations run without issue.
