### ISSUE TITLE
RunPlan does not consider custom cables

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#534]
While trying to write a test using a Pipeline that happened to use a custom input cable, I found that a step I was expecting to reuse an ExecRecord did not use an ExecRecord.  The issue is that RunPlan's `find_ERs` method assumes all cables are trivial.

**Comment by rhliang** [comment]
This issue, and #535, were highlighted by a test I wrote in `sandbox.tests.ExecuteTests`.  I'll leave the test in, commented out, with a FIXME at the top.

**Comment by donkirkby** [comment]
I think we removed support for custom cables, so this can probably be closed. First, check if there's still a test that's being skipped, and remove it.

**Comment by donkirkby** [comment]
Irrelevant since we are removing support for custom cables.
