### ISSUE TITLE
Handle naming conventions for multi-run interface

### ISSUE THREAD

**Issue by jnak-cfe** [cfe-lab/Kive#536]
Naming runs in the multi-run interface should be manipulable on a batch as well as individual basis.

Two interface components were discussed:
 
* At the top of the form, a checkbox with the label "Prefix all names with: " and then a fillable text field (which is disabled when checkbox is unchecked)
* On each run–row, a name field. Defaults to prefix + "_1", "_2", etc.

In each row's name field, the prefix is displayed and is not removable (enforced with JS) so long as the checkbox is checked, but users can edit anything following the prefix. If the checkbox becomes unchecked, the prefix remains in place but becomes editable. If the checkbox becomes checked, each name is checked for the prefix and names which don't match are given the prefix.

**Comment by donkirkby** [comment]
Don't forget that runs have a default name (I think it's pipeline name plus first input's name). If the user has not entered a prefix, we might want to leave the run names as the default.

**Comment by jnak-cfe** [comment]
Wouldn't it be (pipeline name + revision number)? Maybe (pipeline name + input1's dataset)? Or is it actually (pipeline name + input1)?

In any case I think that (pipeline name + revision number) would be a good default prefix.

**Comment by rhliang** [comment]
At the moment it's just pipeline name and input1.  Personally I might suggest 

[pipeline name] ([revision name]) - [input 1]

i.e. including revision *name* instead of revision number.  However, it works fine as it is, and I imagine people might find this cluttered.

**Comment by donkirkby** [comment]
@jnak-cfe, the default is currently pipeline family name plus input 1's dataset name. I think that's reasonable as a default.

Suggested behaviour: leave the run name blank if the user doesn't fill in the prefix field, and use prefix + "_1", "_2", etc. if they fill it in.

Stretch goal: instead of a prefix, have a run name *pattern* that replaces special patterns:

* $0 - pipeline family name
* $1, etc. - input 1, etc.
* $# - run number within the batch

Maybe that's silly.

**Comment by jnak-cfe** [comment]
@donkirkby Not silly, but may cater too much to power users (who know how to use things like sprintf) and not enough to the average user. At that point, they may want to use the API anyway.

**Comment by jnak-cfe** [comment]
The interaction bits are done—it's not quite to @rhliang's spec (`[pipeline name] ([revision name]) - [input 1]`) but with a small backend adjustment I think it's there.

One issue is that input 1 is not set until the user sets it, potentially after already setting a run name. The decision tree for what to do there is probably unintuitive.

I should also test this across browsers as there's a high potential for compatibility issues here.

**Comment by jnak-cfe** [comment]
Just realized there's a small bug when the string is too long for the `<input>` and the user tries to select text.

**Comment by rhliang** [comment]
This is 95% done.  James will close when that last 5% gets finished.
