### ISSUE TITLE
Make multi-run interface flexible for large numbers of inputs and runs

### ISSUE THREAD

**Issue by jnak-cfe** [cfe-lab/Kive#537]
Problem: Pipelines with more than 4-5 inputs do not have enough space to work.

Solution:
Currently, the green down-arrow button tracks the input that it goes to. For larger number of inputs, the table will have to be wider, sometimes wider than the screen. For this reason, the user should be able to scroll this table independently from the rest of the page. For the search dialog, not only the green button, but the whole dialog should track with the active run–input.

Problem: If you have lots of runs on the screen, the search dialog is still positioned above the table, but the active run–input is positioned far below (possibly off the screen)

Solution:
Similar to the first problem, the table needs to scroll independently from the search dialog. No other page elements should scroll and they should overlap the table if needed. As a result, we have to ensure there's enough vertical screen space for the name prefix, description, permissions widget, search dialog, and at least 2 rows of the table to co-exist without the possibility of scroll. We should assume minimum XGA resolution, minus browser chrome, so about 650 pixels.

**Comment by rhliang** [comment]
This is about 75% done.
