### ISSUE TITLE
Allow user to choose 1 dataset to span many runs in multi-run interface

### ISSUE THREAD

**Issue by jnak-cfe** [cfe-lab/Kive#538]
Context: One of the next features of the multi-run interface is the ability to select 1 dataset to span all runs for a single output. We explored several options for this, with consideration going to the burden of visual clutter, the understandability of any exposed controls, and the needed functionality.

We talked about putting auto-fill suggestions inside blank cells (or outside of them), putting a numeric input as part of the search dialog which could specify how many cells to fill, or splitting the green "insert" button into several different "insert" options.

So far, my favoured solution is a variation on the last one. There could be a "options menu" button *within* the "insert" button to expose a number of alternatives.

![multi-run-options](https://cloud.githubusercontent.com/assets/6126553/13611328/e1426cbe-e516-11e5-8954-e4e3726eafd5.png)

* The menu could include icons, or no icons (as icons are not guaranteed to be very helpful for such a specific operation)
* The first option would fill the column but any new rows (runs) would start blank.
* The second option would fill the column and any new rows would already be filled in. If you wanted to stop this behaviour, I guess manually deleting one entry should turn this "off", unless we dedicated a checkbox to turning it off (but I don't think that's necessary)
* Maybe have a third option, "Fill only blank cells in column"?

**Comment by jnak-cfe** [comment]
@rhliang and @donkirkby , wondering if you two are satisfied with this solution?

**Comment by rhliang** [comment]
I like it.  I think "Fill column and auto-fill new entries" might be the more common case, so I would perhaps put that first in the menu?  I defer to you guys for that though.  Offhand I'm not sure we need the third option, at least not yet.

**Comment by donkirkby** [comment]
I suggest we start with the "add" button and the menu button. The menu button only needs one item: "fill column". If the user clicks that before they've finished adding all the runs, they can click it again to fill the rest.

Let's start with that because it's reasonably simple. Once users have tried it out, we can decide whether we need more options.

**Comment by rhliang** [comment]
This is about 2/3 done.
