### ISSUE TITLE
Limit amount of raw Datasets shown when viewing

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#542]
Currently if you try to view a Dataset (which is how you edit its metadata) it tries to read the entirety of the content file.  Limit this to 1000 characters for now.

**Comment by rhliang** [comment]
Now is probably the time for me to read up on Python encoding and decoding.

**Comment by ArtPoon** [comment]
Might already be closed or addressed by another branch - RL will investigate.

**Comment by ArtPoon** [comment]
Generically related to #386
