### ISSUE TITLE
Routinely scan for external data sets and notify users when a file goes missing

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#549]
Originally part of #423.  Perhaps we can deal with this at the same time that we deal with #434, as both involve modifications to the fleet manager's main loop.

**Comment by wrpscott** [comment]
The functionality for an idle task at the Manager level has been implemented and tested in a local branch.
An idle task that checks for missing external files has been implemented.
Also, other issues arising from inconsistent external files were addressed:
Previously, it was possible for an external file to be removed and replaced with a different one.
Kive was not checking the MD5 before starting a run, nor when displaying a run result.
