### ISSUE TITLE
shutil.copyfile does not finish before a Run performs an integrity check on its result

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#550]
Upon deploying v0.7.2, we saw something we had never seen before: the new runs added by MiSeq Monitor looked to be proceeding fine, but then all of them had their first step fail _after_ subsequent steps ran.  A little digging revealed that the input cable connecting step 1's output to step 3's input had a failed integrity check on run 31243.  This is a new check (added in v0.7.2) that makes the input cable check the integrity of any file that it copies into the sandbox for the first time.  Note that this is _before_ the cable actually runs: the cable first copies the file from the database into the sandbox where it was first supposed to appear (in this case, as the output from step 1 -- this was not in the sandbox already because step 1 is reused), and _then_ makes a hard link from that location to the cable's destination (the `input_data` directory of step 3).

Inspecting this failed integrity check indicates that there was an MD5 conflict, and there is a corresponding "evil twin" Dataset associated with it; however, both Datasets have identical contents and MD5 checksums.  Looking in the corresponding sandbox, the file is in fact in place and has the correct MD5 checksum.

However, digging into the log of the worker that performed this failing task shows the following:

```
2016-04-05 16:17:11[INFO]fleet.Worker.receive_and_perform_task(): RunStep(1165784) received by rank 142: Runstep with PS [3: censor_fastq.py]
2016-04-05 16:17:18[ERROR]Sandbox.finish_cable(): [142] Checking file just copied to sandbox for integrity.
2016-04-05 16:17:23[ERROR]Sandbox.finish_cable(): [142] Checking file just copied to sandbox for integrity.
2016-04-05 16:17:23[WARNING]Dataset.check_integrity(): md5s do not agree (old: XXXXXXXXXXXXXX; new: d41d8cd98f00b204e9800998ecf8427e)
2016-04-05 16:17:30[ERROR]Sandbox.finish_step(): [142] PipelineStepInputCable RunComponent id 1165795 failed.
```

(I've removed the original file's MD5).  The telltale clue here is that the new MD5 is `d41d8cd98f00b204e9800998ecf8427e`, which is the MD5 of an _empty_ file!

The problem appears to be that when the integrity check is started, the file has been created by `shutil.copyfile()` but is empty.  This causes the MD5 to be computed as `d41d8cd98f00b204e9800998ecf8427e`, and the logger reports the error.  Then, the routine sets about creating the evil twin Dataset with `Dataset.create_dataset()`, but by this time, `shutil.copyfile` has finished, and the file has been written into place.  This is why the evil twin is exactly the same as the original.

**Comment by rhliang** [comment]
We've decided to disable this new integrity check, restoring the execution algorithm to essentially what it was in v0.7.1, and bump this issue forward until we can sort out a proper solution.  I'll make a v0.7.3 release as soon as possible, and manually clean up the production server's records by:

* removing the runs that failed to run because of the failed integrity check -- this should also remove the failed integrity check
* re-validating all of the old runs that used any ExecRecord affected by this failed integrity check using the `Run.is_successful` method, though we will have to intervene specially for the RunSICs affected by the failed ExecRecord due to problems relating to #551

**Comment by rhliang** [comment]
I haven't been able to reproduce this issue, so am adding a bit of defensive code that checks whether the file has copied three times, waiting a random amount of time (centred at 5 seconds) between checks.  If it fails to copy, we create a failed integrity check.  It will also log at the `warning` level when this happens.

**Comment by donkirkby** [comment]
One of these MD5 failures occurred on the Octomore cluster, so it's not just a problem with Bulbasaur. Rerunning the failed run cleared up the runstep states, but the integrity violation is still in the database. If I look at any of the three runs that the dataset is used in, they all show success in the run status, but an integrity failure in the run outputs. Maybe we should look at the current state of the dataset before displaying an integrity failure.

**Comment by rhliang** [comment]
This just happened again on Bulbasaur too.

**Comment by donkirkby** [comment]
Here's a possible fix that's simple and should have good performance: check the file size before and after calculating MD5. If the size has changed, repeat the MD5 calculation. If the size was zero, we might have to sleep for one second to give the disk write time to complete. Log any changes in file size or MD5 as warnings.

I'd love to be able to reproduce the problem so I could test this fix, but I still haven't been able to.

**Comment by donkirkby** [comment]
I ran the `copy_and_check_md5s` management command from 4 Nov to 14 Nov on both bulbasaur and octomore. Octomore didn't report any errors, but bulbasaur reported 3 errors in the `purge_trash()` method. Unfortunately, the details didn't log properly, so we just know that the errors occurred, not exactly why.

I'll fix the logging problem, and try again.

**Comment by rhliang** [comment]
There's some defensive code now in the Slurm branch; maybe it's worth backporting to the master branch?
