### ISSUE TITLE
Stopping a run crashes fleet

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#557]
I tried stopping a run while it was executing, and the fleet crashed.

```
2016-05-31 16:00:30[ERROR][1441]fleet.Manager.main_procedure(): Manager failed.
Traceback (most recent call last):
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 893, in main_procedure
    self.main_loop()
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 869, in main_loop
    self.find_stopped_runs()
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 757, in find_stopped_runs
    self.stop_run(run_to_stop)
  File "/mnt/data/don/git/Kive/kive/fleet/workers.py", line 785, in stop_run
    for foreman in self.tasks_in_progress:
RuntimeError: dictionary changed size during iteration
```

**Comment by rhliang** [comment]
Ah, I actually didn't know it wasn't allowed to change the size of the dictionary during iteration.

**Comment by ArtPoon** [comment]
The phylogenetic monitoring system just crashed on the cluster with the following complaint:

```
[Bulbasaur:77696] [[29689,0],0]-[[29689,0],1] mca_oob_tcp_msg_recv: readv failed: Connection reset by peer (104)

[Bulbasaur:77696] [[29689,0],0] -> [[29689,0],1] (node: n9) oob-tcp: Number of attempts to create TCP connection has been exceeded.  Can not communicate with peer
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
-------------------------------------------------------------------------- 
```

Could this be related?

**Comment by rhliang** [comment]
No I don't think so, Don is running the development version on his local machine so it wouldn't affect the cluster.

**Comment by donkirkby** [comment]
You can't modify any collection while iterating over it, @rhliang. The most common solution I've seen for dictionaries is to iterate over `.keys()` or `.items()` instead of `.iterkeys()` or `.iteritems()`. For lists, I usually create a new list rather than trying to modify the old one as I iterate over it.
Here's a longer [discussion][].

[discussion]: https://unspecified.wordpress.com/2009/02/12/thou-shalt-not-modify-a-list-during-iteration/
