### ISSUE TITLE
Binary file tester does not identify certain PDFs as binary files

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#567]
Stumbled across this while setting up Kive on the development cluster.  I created a Dataset from a PDF I just happened to have on my desktop, and it barfed when I tried to view it with a `DjangoUnicodeDecodeError`.  I checked, and the `binaryornot` library we use doesn't identify this as a binary file.  A few other PDFs I tried were properly identified.

Perhaps we should use a composite test, that uses both `binaryornot` and the `python-magic` library that Don suggested, to try and spot more stuff.  Or, we could just catch the DjangoUnicodeDecodeError, that might be easier.

**Comment by donkirkby** [comment]
It looks like the `binaryornot` project is active, so I suggest you create an issue [there][bnot]. Is the problem PDF appropriate to include with a public bug report?
If there's an easy improvement to our error handling, let's do that and close this issue. I don't think it's worth trying to be perfect at detecting binary files.

[bnot]: https://github.com/audreyr/binaryornot/issues

**Comment by rhliang** [comment]
Looking at it now, I'm realizing we could have simply caught that error in the relevant view the first time it came up.  My current plan is to do that, and then ditch `binaryornot`.  I'll mention it there, too.

The PDF was a preprint from BioRxiv under Creative Commons, so I think it's reasonable to do.
