### ISSUE TITLE
Inconsistent MD5 for output

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#569]
The fleet crashed because of issue #529, but I can't think of any reason why that output should be nondeterministic. I wonder if the MD5 was calculated before the file finished writing to disk.
The 

> ValidationError: {u'dataset_file': [u'File integrity of "run60488_step3_outputcensored (created by micall on 2016-05-18 08:04:07.923261+00:00)" lost. Current checksum "abc..." does not equal expected checksum "xyz..."']}
> 2016-07-06 21:04:29[INFO]fleet.Worker.receive_and_perform_task(): Worker 100 shutting down.

I checked the MD5 of the output file, and it matches the new MD5, not the one that was stored with the dataset. The new run's id is 92898, and the old run's id is 60488.
- [ ] Check all the current datasets to see if they match their stored MD5 values. I think there's a management command.
- [ ] Try rerunning the step several times to see if it always produces the same output.
- [ ] Calculate MD5's on all the prefixes of the output to see if any of them match the stored MD5.
- [ ] Come up with some way to make MD5 checksum reliable, perhaps related to the fix for #550.

**Comment by donkirkby** [comment]
It looked like this bug had occurred, but I think it was actually #550. The fleet crashed because of an unexpected MD5 when restoring a dataset, but the new MD5 was `d41d8cd98f00b204e9800998ecf8427e`, the MD5 of an empty string. It turns out that the step had crashed because a field in the input file was blank. I expect the input file was only partially written to disk when the step started running.

**Comment by donkirkby** [comment]
A run failed, and it might be a new symptom of this problem. The run was using the MiCall 7.6 pipeline's `trim_fastqs.py`, when it produced this error:

```
Traceback (most recent call last):
  File "/data/kive/Sandboxes/usermicall_run187269_uQEKUk/step2/trim_fastqs.py", line 167, in <module>
    use_gzip=not args.unzipped)
  File "/data/kive/Sandboxes/usermicall_run187269_uQEKUk/step2/trim_fastqs.py", line 91, in trim
    os.remove(filename)
OSError: [Errno 2] No such file or directory: '/data/kive/Sandboxes/usermicall_run187269_uQEKUk/step2/output_data/step2_trimmed2_fastq.raw.censored.fastq'
```

Here is the [source code] that failed:

    cutadapt_args = ['-a', 'file:' + adapter_files[0],
                     '-A', 'file:' + adapter_files[1],
                     '-o', trimmed_fastq_filenames[0],
                     '-p', trimmed_fastq_filenames[1],
                     '--quiet',
                     censored_filenames[0],
                     censored_filenames[1]]
    cut_adapt.check_output(cutadapt_args)
    for filename in censored_filenames:
        os.remove(filename)  # This failed.

I don't understand how this could fail, when the `cutadapt` execution succeeded. I'm recording this here, because I have to remove the run from Kive to make it retry.

[source code]: https://github.com/cfe-lab/MiCall/blob/v7.6/micall/core/trim_fastqs.py#L90

**Comment by donkirkby** [comment]
We've now switched to running jobs under Slurm, and we've rebuilt both Octomore and Bulbasaur using CentOS 7. However, we're still getting intermittent failures. I'm not sure if they have the same cause, but I'm going to record what we know so far.

It looks like the run started at 9:38 and submitted the setup task to Slurm. The task began executing on n1. Then sometime during 9:38, the foreman marked the run as failed. Perhaps, Slurm changed the job state to something like "migrating" or "retrying", then the foreman saw that and interpreted it as failure. In any case, the `sacct` information shows the job running from 9:41 to 11:17, then exiting with return code 102, which means that the run was cancelled. I wonder why it took an hour and 25 minutes to exit?

Here's the `sacct` output for the original run, plus its rerun.

`SACCT_FORMAT='JobID,JobName%50,Start,End,ExitCode' bash -c 'sacct|head -n 1 && sacct |egrep "250591|250790"'`
```
       JobID                                            JobName               Start                 End ExitCode 
635558                                   r250591s\(1\,\)\_setup 2017-05-04T09:41:22 2017-05-04T11:17:06    102:0 
635559         r250591s\(1\,\)driver\[random\-primer\-hcv\.py\] 2017-05-04T11:17:06 2017-05-04T11:17:06      0:0 
642154                                   r250790s\(1\,\)\_setup 2017-05-04T14:31:14 2017-05-04T14:40:39      0:0 
642155         r250790s\(1\,\)driver\[random\-primer\-hcv\.py\] 2017-05-04T14:40:39 2017-05-04T15:19:05      0:0 
642568                             r250790s\(1\,\)\_bookkeeping 2017-05-04T15:19:05 2017-05-04T15:20:45      0:0 
642569                                   r250790s\(2\,\)\_setup 2017-05-04T15:20:46 2017-05-04T15:20:57      0:0 
642570                     r250790s\(2\,\)driver\[sam2aln\.py\] 2017-05-04T15:20:57             Unknown      0:0 
642571                                  run250790\_cable8608145 2017-05-04T15:20:49 2017-05-04T15:21:03      0:0 
642572                                  run250790\_cable8608146 2017-05-04T15:20:49 2017-05-04T15:21:03      0:0 
```

**Comment by donkirkby** [comment]
Over the weekend, we saw several failures similar to the ones in the previous comment.

* run 251280 at 15:29 - step 7 cable 2 migrated from n4 to head node. `sacct` reports it ran for 11s.
* run 251112 at 14:23 - step 8 driver migrated from n0 to head node. `sacct` reports it ran for 11s.
* run 250982 at 13:16 - step 4 bookkeeping migrated from n0 to head node. `sacct` reports it ran for 29s with exit code 1. Error log complains that the run step is in the cancelled state.
* run 251161 at 13:18 - step 2 bookkeeping migrated from n1 to head node. `sacct` reports it ran for 50s with exit code 1. Error log complains that the run step is in the cancelling state.
* run 251322 at 11:02 - step 2 bookkeeping migrated from n4 to head node. `sacct` reports it ran for 40s with exit code 1. Error log complains that the run step is in the cancelled state.
* run 251259 at 10:27 - step 1 setup migrated from n3 to n4. `sacct` reports it ran for 4h 30m 51s with exit code 102 (cancelled).

There were three earlier runs that also failed, but their sandboxes have been purged.

The timing of run 251161 is strange. `sacct` reports that the method ran from 10:11 to 13:09 and bookkeeping ran from 13:17 to 13:18., but the e-mail that the job was cancelled has a time stamp of 13:13. What code sent the e-mail, and when was it running?

**Comment by donkirkby** [comment]
@rhliang is going to add logging details to include the raw state string returned by Slurm when the foreman cancels a job.

**Comment by rhliang** [comment]
This thread appears to be very promising, as the questions from the original poster indicate situations much like ours, and the developer responses all seem like coherent explanations of what's happening with our system and our settings.

https://bugs.schedmd.com/show_bug.cgi?id=2361

Our `slurm.conf` file has no setting for `JobRequeue`, so it must be set to the default value of 1.  We also have `ReturnToService` set to 2, which means that nodes can spring back to life no matter why they went down.  (This explains why we haven't completely run out of nodes.)

**Comment by rhliang** [comment]
This thread is older but indicates that a requeued job would in fact retain the same job ID:

https://groups.google.com/forum/#!topic/slurm-devel/cLlwSh9L_mE

**Comment by rhliang** [comment]
Regarding the timing of run 251161, here is what `sacct` reports for the offending bookkeeping task:

```
(vkive) [kivefleet@octomore logs]$ sacct --duplicates --format "JobID,JobName,Start,End,State,Partition,Submit,ExitCode" -j 649547
       JobID    JobName               Start                 End      State  Partition              Submit ExitCode 
------------ ---------- ------------------- ------------------- ---------- ---------- ------------------- -------- 
649547       r251161s\+ 2017-05-07T13:11:00 2017-05-07T13:13:35  NODE_FAIL  kive-slow 2017-05-07T13:11:00      1:0 
649547.batch      batch 2017-05-07T13:11:00 2017-05-07T13:15:12  CANCELLED            2017-05-07T13:11:00      0:9 
649547       r251161s\+ 2017-05-07T13:17:17 2017-05-07T13:18:07     FAILED  kive-slow 2017-05-07T13:15:16      1:0 
649547.batch      batch 2017-05-07T13:17:17 2017-05-07T13:18:07     FAILED            2017-05-07T13:17:17      1:0 
```

The email being sent at 13:13 is consistent with the first go at the bookkeeping task ending at 13:13:15 and the Foreman quickly noticing it and sending the email.  Later, the relaunched task runs and fails, but like a tree falling in a forest with no one around, nothing happened.

**Comment by rhliang** [comment]
Having done a little bit of reading up on what's happening, I propose the following:

* We leave the system settings for `JobRequeue` and `ReturnToService` the same, so that other users of the cluster can take advantage of those features.
* We start all Kive-related Slurm batch jobs with the `--no-requeue` option.  This prevents the system from doing things that we don't know how to track, but it doesn't preclude us from manually requeuing jobs using `scontrol`.
* If a cable, setup, or bookkeeping task terminates with `NODE_FAIL`, we manually requeue the task.  Because of this, we should also start our batch jobs with the `--open-mode=append` option, so that the stdout and stderr logs will contain details of what happened.
* If it occurs on a driver task (i.e. one that runs external code), we:
   * do what we're currently doing and consider the job cancelled, OR
   * clean up the step sub-sandbox a bit and requeue it, OR
   * create another step sub-sandbox and redo the whole step there

In that last step, option 1 is the easiest to implement but means the most cancelled jobs.  Option 2 seems hard to implement because we have no way of really controlling what goes in in the step sub-sandbox.  Option 3 will require some work -- I'll look into it to gauge roughly how much -- but seems like the best option in the long term.

**Comment by donkirkby** [comment]
I agree with @rhliang's plan, but we should also do some stress testing to figure out why Slurm is terminating so many jobs with `NODE_FAIL`. Maybe we need to adjust the [`SlurmdTimeout`].

>The interval, in seconds, that the Slurm controller waits for slurmd to respond before configuring that node's state to DOWN. ... The default value is 300 seconds.

I'm not sure that ours is a big cluster, but the Slurm docs have this [advice]:

> The configuration parameter SlurmdTimeout determines the interval at which slurmctld routinely communicates with slurmd. Communications occur at half the SlurmdTimeout value. The purpose of this is to determine when a compute node fails and thus should not be allocated work. Longer intervals decrease system noise on compute nodes (we do synchronize these requests across the cluster, but there will be some impact upon applications). For really large clusters, SlurmdTimeout values of 120 seconds or more are reasonable.

We might also need to tell Slurm that it's launching too many jobs at once.

[`SlurmdTimeout`]: https://slurm.schedmd.com/slurm.conf.html
[advice]: https://slurm.schedmd.com/big_sys.html

**Comment by donkirkby** [comment]
In addition to the jobs that Slurm marked as NODE_FAIL and requeued on Sunday, I also found three jobs that were killed by `oomkiller`.

```
[don@octomore ~]$ sudo grep -i "killed process" /var/log/messages*
/var/log/messages:May  7 12:28:53 octomore kernel: Killed process 185631 (bowtie2-align-s) total-vm:3781220kB, anon-rss:3534720kB, file-rss:0kB, shmem-rss:0kB
/var/log/messages:May  7 12:32:33 octomore kernel: Killed process 76862 (bowtie2-align-s) total-vm:3786380kB, anon-rss:3531212kB, file-rss:152kB, shmem-rss:0kB
/var/log/messages:May  7 12:41:53 octomore kernel: Killed process 5410 (bowtie2-align-s) total-vm:3790744kB, anon-rss:3532404kB, file-rss:0kB, shmem-rss:0kB
```

```
[don@octomore ~]$ sacct -j643016 -j643102 -j647189 -o Jobid,jobname%50,state,exitcode,start,end,nodelist --duplicate
       JobID                                            JobName      State ExitCode               Start                 End        NodeList 
------------ -------------------------------------------------- ---------- -------- ------------------- ------------------- --------------- 
643016         r251018s\(1\,\)driver\[random\-primer\-hcv\.py\]     FAILED      1:0 2017-05-07T12:14:38 2017-05-07T12:28:31        octomore 
643016.batch                                              batch     FAILED      1:0 2017-05-07T12:14:38 2017-05-07T12:28:32        octomore 
643102         r251054s\(1\,\)driver\[random\-primer\-hcv\.py\]     FAILED      1:0 2017-05-07T12:19:54 2017-05-07T12:41:20        octomore 
643102.batch                                              batch     FAILED      1:0 2017-05-07T12:19:54 2017-05-07T12:41:20        octomore 
647189         r251307s\(1\,\)driver\[random\-primer\-hcv\.py\]     FAILED      1:0 2017-05-07T11:28:47 2017-05-07T12:32:06        octomore 
647189.batch                                              batch     FAILED      1:0 2017-05-07T11:28:47 2017-05-07T12:32:06        octomore 
```

**Comment by donkirkby** [comment]
Octomore processed two MiSeq batches over the weekend, and we saw similar NODE_FAIL scenarios to last week on 33 Slurm tasks. There were two clusters of them at 2017-05-13 12:33 and 2017-05-14 10:47. I didn't find any `oomkiller` messages this time.

**Comment by donkirkby** [comment]
We finally saw two tasks in the NODE_FAIL state on Bulbasaur during yesterday's test. One job seems to have been requeued fast enough that Kive didn't notice it. The other one got cancelled by Kive, but didn't write two sets of log files.

Here's a command to report all tasks in NODE_FAIL or CANCELLED states since the start of the test:

    sacct -snf -sca -ukivefleet -ojobid,jobname%50,state,exitcode,start,end,maxrss -S 2017-05-15T14:00

**Comment by donkirkby** [comment]
Since we added the code in #687 to wait a few minutes for NODE_FAIL to retry, we seem to have solved this issue, so I'm closing it.
