### ISSUE TITLE
Permissions error not displayed when choosing inputs

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#570]
Steps to reproduce:
1. Create a pipeline with no groups allowed.
2. Go to the Analysis page, and choose that pipeline.
3. Choose some inputs.
4. Grant access to Everyone.
5. Click the Go button.

Expected result: the Choose Inputs page should be displayed with an error message like "Everyone could not be granted access."

Actual result: the Choose Inputs page was displayed again, but there was no error message.

**Comment by wrpscott** [comment]
this is closed by  	876ffed
