### ISSUE TITLE
Input selection screen doesn't scroll when there are many possible inputs

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#580]
Discovered this while I was testing changes to the Python API for #572.  This is what it looks like:

![toomanydatafiles](https://cloud.githubusercontent.com/assets/5862525/17007723/bcd27d36-4e9f-11e6-810c-a1edb1c92f90.png)

**Comment by jnak-cfe** [comment]
Yep, makes total sense.
I'll tackle this one right away. This may require an AJAX request on window resize events.
