### ISSUE TITLE
Multi run interface: improve the way the search table is reloaded on window resize

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#581]
Following up to the basic implementation of #580, there are a number of things that could be improved upon.

* [x] Reduce the returned page size on initialization to 6-8 instead of 25, which is always too many.
* [x] When the page size is being reduced, not expanded, remove the overset rows and modify the object state, but do not trigger an AJAX call.
* [ ] The way PermissionsTable currently works, when you are *not* on page 1 of a search results list and you modify page_size, there is no way to keep the first item on the page constant during this change, since the page must always start at a multiple of page_size. We could either change pagination to be more flexible, or drag the user back to page 1 every time page_size changes.
* [ ] If this entire approach results in a substandard user experience, we could just have a super-long table (maybe cap it at 100 or 200 per page) and use an inset scrollbar instead. (This idea is up for discussion.)

**Comment by donkirkby** [comment]
There is another mode for pagination that allows you to specify start and stop indexes instead of page size and number. However, I think the API can only support one mode, not both. We'll have to check to be sure.
Another option when resizing would be to calculate the index of the first item on the old page, then display the new page that should contain that item. At least that would keep the user near the same position. Remember that new items can appear in the database, so there's always a possibility of the page contents changing.

**Comment by jamesnakagawa** [comment]
@donkirkby , the page currently has close to that behaviour. The problem is that it doesn't have memory, so if the page size changes multiple times as the user is resizing the window, it first does it for the first item on the list, and then does it for the first item on the *resulting* list, and if it is resized enough times always ends up back on page 1.

**Comment by rhliang** [comment]
This is the paginator that Don was talking about, I think: 

http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination

A single ViewSet generally supports a single paginator.  That can be worked around by creating a new list view within the ViewSet, but I think just modifying our code to accommodate limit offset pagination wouldn't be too hard.

**Comment by donkirkby** [comment]
I think the current method sounds good enough for now, @jamesnakagawa. I suggest we close this issue and open a new one if we find it frustrating. I don't think page resizing happens that often.

**Comment by jamesnakagawa** [comment]
Point taken, @donkirkby. Although, personally, I've been spending _hours_ at my desk resizing the window repeatedly.
