### ISSUE TITLE
Runs page is slow

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#582]
Perhaps adding the run batch slowed down some of the queries. Do some profiling, and speed it up again.

**Comment by rhliang** [comment]
I'll be interested to see what you find.  The Runs page is nearly entirely unmodified; there's just an extra field on each Run now for its RunBatch.  I scanned through the code and didn't see anything obvious.  Perhaps some hidden recursive call to `clean` somewhere.

**Comment by donkirkby** [comment]
I didn't find anything that had obviously changed to make things slower, maybe it was just my imagination.

However, I made it roughly twice as fast by removing some unnecessary lookups for _runstate and by prefetching the run inputs.
