### ISSUE TITLE
Drop-down menu for add button not appearing

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#583]
When I start a run batch, I can only use the regular add button or double click on datasets. The drop-down menu button next to the regular add button doesn't do anything when I click on it. I have tried it with both Chrome 51.0.2704.106 and Firefox 47.0 on Ubuntu 14.04.
If this isn't easy to fix, I think we could release with just the regular add button.

**Comment by jamesnakagawa** [comment]
This was just an unintended consequence of a line I added to prevent the search results table from messing up the page before the AJAX update had completed. However, it now removes rows without an AJAX call, so the line shouldn't be necessary.
