### ISSUE TITLE
Don't clear filters when changing input columns

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#585]
Steps to reproduce:
1. Go to the analysis page, and choose a pipeline with more than one input.
2. Click on the green + button in the first input column.
3. Add some dataset filters.
4. Click the grey + button in the second input column.

Expected result: select new column for adding inputs, but don't change the dataset filters. The only filter that might change is the compound datatype.
Actual result: dataset filters are completely reset.

This surprised me, particularly when I had just added several inputs to the first column. It was only later that I realised you were storing a separate set of filters for each column. That wasn't clear, and I'm not sure that it's helpful.
If we just leave the filters alone, and only change the compound datatype filter, the user can add and remove filters as they wish.

**Comment by jamesnakagawa** [comment]
Actually, this is behaviour that you had suggested way back in #488, @donkirkby (haha!)
The dialog's state is maintained separately for each column (input). See lines 297-358 of `choose_multi_inputs.js`.
Regardless of what we thought before, though, we should be implementing the best, most useful and intuitive behaviour. Can we discuss at next meeting?

**Comment by rhliang** [comment]
One suggestion for when we do have that meeting: perhaps two kinds of filters, one that persists across columns and one that doesn't?  From the UI, this could take the form of having a checkbox for "apply to this column only", say, and the resulting filter could be a slightly different colour?

**Comment by jamesnakagawa** [comment]
Sure, @rhliang, but first I think we should decide if this is actually a useful feature, and if it is, then we need to decide if disabling it is also a useful feature!

**Comment by donkirkby** [comment]
That was past me, @jamesnakagawa. That guy has a lot of dumb ideas.
Yes, let's talk about it at the next meeting. Keep in mind the [principle of least astonishment][surprise].

[surprise]: https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by donkirkby** [comment]
Conclusion from meeting: leave filters alone when changing columns, just change compound datatype if needed.
