### ISSUE TITLE
Multi-run search table shows error erroneously

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#587]
Steps to reproduce:
- Choose datasets to fill inputs for a new run.
- Add a second row (run) to the interface.
- Click the green "+" again.

Expected behaviour:
The search table appears without issue.

Actual behaviour:
The search table complains that there is no room to display rows, even though there is.

**Comment by donkirkby** [comment]
Closed by 5b3ee21a0872cf1c0a256163688cdd95396ce927.
