### ISSUE TITLE
Dataset filters for run batch

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#588]
I noticed a few glitches with the extra filters on this page.
* [ ] "Creator" menu is empty.
* [x] "Date added" has a "Custom..." entry, but it's disabled.
* [x] "Date Last Run" doesn't seem to do anything.
* [x] Having two date fields is confusing, consider dropping "Date Last Run" or change the naming. Perhaps "Added any time", "Added today", and "Added this week" could be in one menu, and "Last run any time", "Last run today", and "Last run this week" could be in the other.

**Comment by donkirkby** [comment]
* Remove "Date last run" until it can be implemented.
* Remove the "Custom" entry.
* Double-check on the "Creator" issue.
* Change the style of the "default" options so they look different from the other options.
* Ignore the fourth point for now.

**Comment by jamesnakagawa** [comment]
James and Don to review remaining task.

**Comment by donkirkby** [comment]
The problem is that the Creator menu makes an AJAX call for all datasets, then builds a list of unique creators. My database has several thousand datasets, and the AJAX call takes a very long time.
@rhliang will add a new API call to list users.
@jamesnakagawa will switch to calling it.

**Comment by jamesnakagawa** [comment]
@donkirkby, can you confirm using your thousands of datasets that this works now?

**Comment by donkirkby** [comment]
Works fine. Closing the issue.
