### ISSUE TITLE
Dataset selection goes onto the wrong page when moving to next column

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#589]
Steps to reproduce:

1. Upload enough datasets to require paging through the appropriate datasets while choosing an input (in my case there are 5 pages), and choose one from the last page

Expected behaviour:
selector moves to second column, starting at page 1

Actual behaviour:
selector moves to second column but starts at page 3

More weird stuff happens when I remove the Uploaded filter too.

**Comment by jamesnakagawa** [comment]
I think this is because dialog state does not keep track of all pagination variables. I'll have a look.

**Comment by donkirkby** [comment]
#585 will fix this issue.
