### ISSUE TITLE
Add key events to dataset search filters

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#591]
1- backspace/delete will delete a filter when it is in focus
2- arrow keys will move focus to filters (or backspace when pressed from input box)
3- check and see what gmail does when you press "tab"

**Comment by donkirkby** [comment]
Definite improvement, but I suggest you make the backspace key delete the last filter when the cursor is at the start of the field. Currently, it focuses on the last filter, and then you have to type backspace a second time to delete the filter.

**Comment by jamesnakagawa** [comment]
Initially, I had done this intentionally to avoid the user being surprised by the behaviour.
However when comparing it to Gmail, I can see that your suggestion has precedent, @donkirkby, so I’ll make the change.

**Comment by jamesnakagawa** [comment]
Should be good—but before presuming this issue closed this time, I'll wait until others have had time to review.

**Comment by donkirkby** [comment]
It's a thing of beauty. Closing the issue.
