### ISSUE TITLE
Add new filter style to other search interfaces

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#592]
Investigate how much work it would be to extend the search filter interface style to other pages in Kive.

**Comment by jamesnakagawa** [comment]
Tried to implement this today. It affected a lot of pages, so hopefully I didn't break anything.

It affected:
```
method/method_families.html
method/methods.html
method/resource_revisions.html
method/resources.html
pipeline/pipeline_families.html
pipeline/pipelines.html
sandbox/choose_inputs.html
sandbox/choose_pipeline.html
sandbox/runbatch.html
sandbox/runs.html
sandbox/view_results.html
librarian/datasets.html
metadata/compound_datatypes.html
metadata/datatypes.html
```

A couple things I noticed along the way (some of these are notes for myself):

* method/resources.html: unknown filter key: filename
* sandbox/choose_inputs.html: deleting a filter with a key event does not clear the corresponding <select> element
* sandbox/runbatch.html: advanced search fields may not make sense. didn't they all start at the same time?

**Comment by jamesnakagawa** [comment]
I also should mention that I inlined any Javascript that was only being used on one page. This involved about a million child classes of PermissionsTable. Any objectors, declare thyself now!

**Comment by donkirkby** [comment]
I fixed the unknown filter key yesterday in commit d68f2c3d262f0f9e59b6dac2f58509190c2e172c. Don't know how we never noticed that was missing.

When you say you inlined Javascript, do you mean you moved it into an HTML template? That's going to make it harder to run JsHint, because my IDE is currently configured to run JsHint on `*.js` files. I tried running JsHint on some HTML templates, but it was totally confused.

I propose the following options, feel free to add others:
1. Leave most of the JavaScript in `.js` files so we can easily run JsHint on it and write unit tests for it.
2. Figure out whether JsHint can be persuaded to do something useful with Javascript that's mixed in with HTML and Liquid template tags, then inline whatever Javascript can be.
3. Measure the faster load time or whatever other benefits we get from inline Javascript, and decide whether it's worth losing the JsHint coverage.
4. Consider some kind of preprocessing step that inlines the Javascript from its separate files. It could also do other things like adding a checksum to the file name to avoid stale cached Javascript and running minify.

Whatever we choose, can we wait until after we've released 0.8 to make a big change like this?

**Comment by jamesnakagawa** [comment]
I moved it into the HTML template, yes.
I mostly did it to make editing easier. I was being bothered by having to juggle multiple files with few lines. But I see your point about JSHint.
Yes, it sounds reasonable to release 0.8 without this.

**Comment by jamesnakagawa** [comment]
I wonder, since the majority of what I inlined from separate files were PermissionsTable subclasses:

Is there some better way of organizing these? Could we just add them to `permissions.js`, or perhaps collect them all into a `tableclasses.js`? Seems to be quite a bit of redundancy between them.

**Comment by donkirkby** [comment]
I quickly looked at `datasets.js` and `datatypes.js` as two reasonably simple examples. Most of what I saw was either defining columns in the table or messing with the search filters. From my brief review, I couldn't see any obvious ways to improve the column handling, but the filter handling did look like it might be able to move into the `FilterSet` class. If you want to tackle that as part of this issue, go ahead.

As for moving the code for individual screens into the permissions module, that feels strange to me. Usually I like to keep the related model, view, and templates code all together in the same app. We may have to accept some level of awkwardness when working on a web application. It's always a pain to work with a mix of HTML, Javascript, Python, and SQL. At least Django hides the SQL reasonably well. Next time I'm at your desk, let's go through some of the pain points to see if we can improve the workflow.

Also let me know if I've misunderstood what you're trying to do.

**Comment by jamesnakagawa** [comment]
OK, I've put the JS back into separate files (albeit in a slightly different wrapper) and the inline portions are down to basically 3 lines (2 instantiations and a call to `reloadTable`). I feel I could get it down to 1 instantiation and no function call by further integrating AjaxSearchFilter with other classes, but we're in a good place for now.

**Comment by donkirkby** [comment]
Looks great, @jamesnakagawa. Thanks for cleaning that up.

**Comment by jamesnakagawa** [comment]
AFAIK this is done. Closing.
