### ISSUE TITLE
Revisit expanding search table screen space

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#594]
In the multi-run interface, aim for 8-10 rows of search results visible without scroll/pagination.

**Comment by jamesnakagawa** [comment]
@rhliang, can you do a fresh pull and check if your concerns have been addressed?

**Comment by rhliang** [comment]
Yeah it looks pretty good at this size:

![datasetsearchsizebetter](https://cloud.githubusercontent.com/assets/5862525/17114093/539a8a9a-5262-11e6-857d-3a5050153270.png)

**Comment by jamesnakagawa** [comment]
Awesome!
