### ISSUE TITLE
Refactor Python API's representation of CompoundDatatypes?

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#596]
Currently the Python API's CompoundDatatype wrapper object sets the name of the object to be the representation.  I think this was probably written before CompoundDatatypes actually had names themselves.  Should we refactor this so that the name gets stored as `self.name` while the representation gets stored as `self.representation`?  If so, what do we do about the `__str__` method and its kin (`__unicode__`, `__repr__`, etc.)?

**Comment by donkirkby** [comment]
I suggest we store the name field as `self.name` if it has a value, otherwise put the representation field into `self.name`.
