### ISSUE TITLE
Dataset directories are still being created with the wrong permissions on Bulbasaur

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#599]
Just had this problem (probably because the month just rolled over): the fleet was unable to write Datasets to the directory `/data/kive/Datasets/2016_08` because write permission was not granted to the group (which is `kive`).

**Comment by rhliang** [comment]
Before I forget, wanted to record here that I set the `sgid` bit on `/data/kive/Datasets`, which *should* fix this issue.  Let's keep an eye on it over the next couple of days as we enter September.

**Comment by donkirkby** [comment]
Just to clarify, @rhliang changed the `sgid` bit some time in August.

**Comment by rhliang** [comment]
We're almost at October so keep an eye out.

**Comment by rhliang** [comment]
Note to self: check that the changes made to apache's umask were on Bulbasaur and not just on Octomore.

**Comment by rhliang** [comment]
The changes I thought I had made were on Octomore, not on Bulbasaur.  I've now made the changes and restarted apache on Bulbasaur.  Now we wait until October rolls around.

**Comment by donkirkby** [comment]
October rolled around and... FAIL!

```
ls /data/kive/Datasets/ -l
total 47996
drwxrwsr-x 2 apache    kive    4096 May  5  2015 2014_08
drwxrwsr-x 2 apache    kive   20480 Dec 22  2015 2015_05
drwxrwsr-x 2 apache    kive    4096 Dec 22  2015 2015_06
drwxrwsr-x 2 apache    kive   36864 Mar  8  2016 2015_07
drwxrwsr-x 2 apache    kive    4096 Dec 22  2015 2015_08
drwxrwsr-x 2 apache    kive    4096 Dec 22  2015 2015_09
drwxrwsr-x 2 apache    kive   28672 Dec 22  2015 2015_10
drwxrwsr-x 2 apache    kive   20480 Mar 10  2016 2015_11
drwxrwsr-x 2 kivefleet kive 1277952 Sep  9 03:27 2015_12
drwxrwsr-x 2 kivefleet kive 2637824 Sep  9 01:42 2016_01
drwxrwsr-x 2 kivefleet kive 1638400 Apr 12 15:35 2016_02
drwxrwsr-x 2 kivefleet kive 8843264 Apr 28 02:19 2016_03
drwxrwsr-x 2 kivefleet kive 8523776 Sep  8 22:08 2016_04
drwxrwsr-x 2 kivefleet kive 7892992 Sep  8 19:35 2016_05
drwxrwsr-x 2 kivefleet kive 5414912 Sep  8 18:50 2016_06
drwxrwsr-x 2 kivefleet kive 2719744 Sep  8 17:56 2016_07
drwxrwsr-x 2 apache    kive 4493312 Sep 13 17:32 2016_08
drwxrwsr-x 2 kivefleet kive 5472256 Sep 29 21:50 2016_09
drwxr-sr-x 2 apache    kive   12288 Oct  2 11:21 2016_10
```

Because all the old runs were finished processing on the MiCall pipeline, the fleet didn't create any datasets between midnight Oct 1 and 11:21 Oct 2 when the MiSeq monitor uploaded datasets for a new run. Then when the fleet started to process a run, it couldn't create new datasets, because the `2016_10` folder wasn't writable by the group.

**Comment by rhliang** [comment]
Scotty and Don talked about making a Manager idle task that will create the next month's Dataset directory ahead of time, which seems to be the only way we're ever going to solve this problem.

**Comment by wrpscott** [comment]
A directory is now preventatively made by Kive in advance,   59fce42
