### ISSUE TITLE
Cannot restore output from failed step

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#602]
Shouldn't we be able to recreate outputs from failed runs? It might be useful if we're trying to debug a pipeline. Currently, it refuses to recreate an output if the previous run had a nonzero return code or if the output didn't match the compound datatype.

Steps to reproduce:

1. Write a script that has a nonzero return code, so it will be marked as failure. Make it write something to its outputs, though.
2. Wire it up in a pipeline.
3. Run the pipeline.
4. Look at the results. See that the step is a failure, but you can view the output. Look at the dataset id for the output.
5. Launch a Django shell, and purge the dataset using the id.

        $ ./manage.py shell
        >>> from librarian.models import Dataset
        >>> dataset = Dataset.objects.get(id=YOUR_DATASET_ID)
        >>> dataset.dataset_file.delete()

6. Refresh the results page. The output should now be listed as *removed*.
7. Go back to the list of runs and click the rerun link for the run.
8. Wait for the rerun to complete, and then look at the results.

Expected results: the step should still be a failure, but the output should be restored.

Actual results: the step is a failure, but the output is listed as *removed*.

**Comment by rhliang** [comment]
Hm.  I suspect this is a foible of the way we reuse steps.  Did the second run actually run anything or did it reuse an ExecRecord?

Either way, I agree that we should be able to do this.  I suspect the place to look will be in the `get_suitable_ER` methods.

**Comment by donkirkby** [comment]
For now, when an external dependency causes failures, an admin will have to remove the failed runs, fix the external dependency, and rerun.

Other suggested fixes:
* automatically rerun all failed steps when rerunning a pipeline
* user option to force reruns when rerunning a pipeline

We discussed this and decided that it would be better to spend the time on containing external dependencies within docker containers than adding features to the reruns.
