### ISSUE TITLE
Should we use smtplib to send emails when Kive crashes?

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#604]
For discussion at our next meeting today.  Art's phylogenetic monitoring systems use `smtplib` to send messages when a report is generated, and in my limited experience it's pretty easy to use.  We could have the fleet manager do the same thing when it crashes, or maybe even when it triggers a purge or something.

Notifications to consider:
- [ ] web server errors
- [x] fleet errors
- [x] ~~backup errors (e.g. using `MAILTO` in `crontab`)~~
- [x] Micall errors

Other tasks:
- [ ] streamline error reporting within Kive code so we don't get spammed

**Comment by donkirkby** [comment]
I think we can configure the logger to send an e-mail to administrators whenever an event above a given level is logged. Sending e-mails for ERROR or above seems like a good place to start.

**Comment by donkirkby** [comment]
Another notification to consider: crontab backups.

**Comment by rhliang** [comment]
Just took a look through the code, and while we should still definitely review logging output before we release v0.9, for the moment we could simply activate the mail handler on Bulbasaur and it would only be sending us a few messages we didn't care that much about.  Everything else it sent us would be good for us to know.  Next time we have some downtime, I'll see about setting it up.

**Comment by rhliang** [comment]
Fatal fleet errors are now being emailed to us through Django's logging system.  The other kinds of errors might warrant using `smtplib` since they're outside of Django.

**Comment by rhliang** [comment]
Note: we crossed out the backup task message as that's basically external to Kive.  If the time comes to set those up, the appropriate way is probably using `crontab` and the `MAILTO` field.

**Comment by donkirkby** [comment]
Error reporting is good enough for now. Reopen if we have problems.
