### ISSUE TITLE
Provide hints for run names

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#608]
Users didn't seem to know that they could leave the run names blank, so they were copying and pasting file names into the run names.

Suggestion: display hint text with the default run names, then the user can override that if they want to, but may not feel obliged to type something in the field.

Now that we're showing run name and batch name in the table, does it make sense to offer a run name prefix? Should we just have fields for batch name and run name? Do we just want to use the pipeline name as the batch name? Should we add a date or number to the batch name?

**Comment by jamesnakagawa** [comment]
@rhliang, what is the default name for runs? And do we want the default prefix?

**Comment by rhliang** [comment]
In the backend, the default name is simply "", the blank string.  I think the default name for runs was always the name of the pipeline and then the name of the first input, but I believe that was done in Javascript.

**Comment by donkirkby** [comment]
![Wrong!][wrong]

Actually, the default name for a run is calculated in the back end. [`Run.display_name()`][display] calculates it as the pipeline name and input name or date.

[wrong]: https://media.giphy.com/media/3oz8xLd9DJq2l2VFtu/giphy.gif
[display]: https://github.com/cfe-lab/Kive/blob/v0.8.5/kive/archive/models.py#L508

**Comment by rhliang** [comment]
Oh yeah I forgot.  Now I will stare at this Trump GIF for one solid minute as penance.

**Comment by rhliang** [comment]
Update: I gave up early.

**Comment by jamesnakagawa** [comment]
Ahhhhh!!!

**Comment by jamesnakagawa** [comment]
So it's "PipelineName on FirstInputDatasetName" (with spaces), or if there's somehow no dataset, "PipelineName at (date)"

What if there's already a run with that name? Does it add _1, _2, etc?
Since the front-end will take over default naming, can I propose:

- Pipeline name + date as the default prefix
- Simply _1, _2, _3 as each run name

This is the simplest way I can think to avoid naming conflicts.

**Comment by rhliang** [comment]
Duplicate names are allowed, so we've just been letting them happen, and we tell them apart by the run date.  I think working a timestamp into the default suggested name would be a good idea.

**Comment by donkirkby** [comment]
As Richard said, run names don't have to be unique. I suggest we leave the run name blank unless the user puts something in, and just display hint text that shows what the display will be. We currently store the run name as blank by default and calculate the display name when we retrieve from the database.

We already store the date in a separate field, so I'm not sure how it's useful in the run name.

**Comment by jamesnakagawa** [comment]
Ok, just need 1 more thing to implement this: The timestamp in the relevant format exposed to the template in `sandbox/views.py`.

**Comment by donkirkby** [comment]
Shouldn't be a big deal to do that, but couldn't you use the browser time? It's only going to be a placeholder until they fill in the first input, right?

**Comment by jamesnakagawa** [comment]
Yes, I could use that, but I _do_ need to know the correct date/time format.

**Comment by jamesnakagawa** [comment]
Got it. Okay, will do.
“PipelineName on FirstInputDatasetName"

**Comment by donkirkby** [comment]
Don't worry about the date, I now see there are four possible results for display name:

1. custom name entered by user
2. pipeline name + " on " + first input name
3. pipeline name + " at " + time queued
4. pipeline name

I suggest you use option 4 to start, then option 2 once the first input is selected. I think you can skip option 3.

**Comment by jamesnakagawa** [comment]
OK, implemented as specified by @donkirkby
