### ISSUE TITLE
Process active runs before pending runs

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#609]
When the MiSeq monitor requests a large number of reruns, it can starve the active runs. Because all of the pending runs are reruns, there's no pause for the active runs to advance. Switch the priority so that pending runs are only processed after trying to advance all the active runs that have completed a step.

**Comment by rhliang** [comment]
Looking at the code now, in the `main_loop` method of Manager, the call to `find_new_runs` (which is what handles pending runs) does already occur after the call to `wait_for_polling` (which is what watches for finished tasks).  Starvation occurs when the jobs arrive faster than `find_new_runs` can clear them.  So, I think a reasonable way to implement this change is to modify `find_new_runs` to either:

 - stop after a handling single pending run (or a fixed number of them), thus causing the loop to go to the beginning
 - interleave handling pending runs with more calls to `wait_for_polling`

The first is definitely more elegant.  So long as the call to `find_stopped_runs` isn't prohibitive, then I would think the first way is the better way.  Even if the call to `find_stopped_runs` is a problem, I think we could work around that by only looking for stopped runs after a certain time interval has elapsed.

**Comment by rhliang** [comment]
Another option that I should have noticed is to modify `find_new_runs` to only look for new runs for a fixed interval of time.  That's already happening in `find_new_runs`, `wait_for_polling`, and `assign_tasks`.  This would be a pretty trivial change.
