### ISSUE TITLE
Run steps sometimes hang

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#613]
Every few days, we will see a run that gets stuck and never advances. It looks like the output files have been created in the sandbox, but the manager hasn't advanced the pipeline. It looks like the child process may have completed, and either the worker didn't notice, or the manager didn't receive the worker's MPI message.

**Comment by rhliang** [comment]
Did a little bit of digging on the three runs that are currently stuck.  In all three cases, I tracked down which host was running the step that stuck, and all of them appear to have actually finished the step (checked the output from `ps` and in no case was there a corresponding process).

Also, all three of the jobs that stuck were running tasks on node 0.  Perhaps a coincidence?  Maybe not?  I'll keep watching.

**Comment by rhliang** [comment]
A likely culprit is the `stdout` and `stderr` threads, that monitor the console output of the step subprocess.  As a first step let's do away with the threads (we aren't using that functionality anyway) and see if that solves the hanging problem.

**Comment by rhliang** [comment]
We've decided to look into Slurm (#508) as a way to sidestep this altogether (hopefully).

**Comment by rhliang** [comment]
As part of #508, I'm going to do away with the threads that monitor `stdout` and `stderr` for a running step.

**Comment by rhliang** [comment]
Slurm to the rescue (hopefully)!  Closing.
