### ISSUE TITLE
Convert drydock files to TypeScript

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#616]
Summarizing yesterday's meeting, TypeScript has numerous advantages:

* Allow all variables to be optionally typed
* Use ES6 syntax and features while still compiling to ES5
* Keep classes in modules, bundle all modules during compilation

There's just 1 disadvantage: TypeScript must be compiled during the install process, which can be done conveniently if the user has `node` and `npm` installed using command `npm install` in the root Kive directory.

As per suggestion I've started the conversion on a new branch called TypeScriptConversion and will merge back when tests all run and functionality is back up to pre-TypeScript levels.

**Comment by donkirkby** [comment]
I don't think you need to get everything running, @jamesnakagawa. I suggest you convert a few scripts, try adding a feature, and then we can talk about what you liked and what you didn't.

**Comment by jamesnakagawa** [comment]
I'm now done in my branch for this task - will discuss at meeting today.

For some reading on the coming changes, here are some resources:

[Overview of new ECMAScript 6 features](http://adrianmejia.com/blog/2016/10/19/Overview-of-JavaScript-ES6-features-a-k-a-ECMAScript-6-and-ES2015/)
[TypeScript docs](https://www.typescriptlang.org/) - pretty quick read (to get 95% of the useful features, anyway)
[SystemJS (module loader) docs](https://github.com/systemjs/systemjs/blob/master/README.md)

**New installation instructions**

[NodeJS](https://nodejs.org/en/download/) must be installed first.

* To install dependencies (incl Typescript), compile pngicons, Typescript files, and Sass files: `npm install` in root dir
    * _note: there's currently a stubborn error that will come up on `dialogs.tests.ts`. it can be safely ignored for now._
* To compile Typescript and watch for changes: `tsc -w` (or set up PyCharm to do this automatically)
* To run the test server: `browser-sync start --server`

**Comment by jamesnakagawa** [comment]
I'm closing this issue for now. Let me know if you run into any hiccups!
