### ISSUE TITLE
Affordance for creating outputs

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#619]
In the last two days, both Scotty and Vincent had to ask me how to create outputs when creating a pipeline. We should make it clearer, so here are some options to think about:

1. Always display the output target region.
2. Add outputs the same way we add inputs: from the menu. This is easier now that outputs can be detached from their cables. The only down side is that you have to pick the compound datatype instead of just dragging from a method.
3. Switch the input creation to match the output creation, possibly with a creation region always visible. This would require dragging cables from either end.

**Comment by jamesnakagawa** [comment]
I'm a fan of the second option because it's the most consistent with our mental model. However, we could make this a redundant feature, since the existing method of adding outputs is faster to use & doesn't clutter the space.

**Comment by rhliang** [comment]
I also vote 2.

We discussed briefly in an informal meeting that with option 2 you could just create a "generic" output that then deduces its CDT from the Method output that it gets connected to.

The issue of an unconnected output node (i.e. one that is floating and not cabled to any step output) might come up; one proposal to handle this is to allow it to float but raise an error message on submission if there are any such orphaned outputs.

**Comment by donkirkby** [comment]
Floating outputs already exist and are handled as you describe.

**Comment by jamesnakagawa** [comment]
This is now implemented as of b42656b42117a3f04e179ac8ba8102a77526d315.
