### ISSUE TITLE
Fix places where we build HTML in strings

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#621]
I stumbled across a place where we're doing this in the add method form. This is a problem, because a user who puts HTML code into a description field can break the forms where that description is displayed. In the unlikely event that a user is malicious, they can use the technique to access data they shouldn't be able to.

Steps to reproduce:

1. Create a new code resource with the name `x</option></select>y <em>z</em><select name="x"><option>flap`.
2. Go to the methods page, and click the Add new method button.
3. Click the + button under Dependencies.

Expected behaviour: the code resource with the strange name should appear in the list.

Actual behaviour: the last code resource in the list is named "x", the dropdown is followed by the letter "y", and there is a second dropdown with the item "flap" in it.

* [x] Review with the developers why this is a problem, and jQuery techniques to safely build HTML from user data.
* [ ] Search all `.js` files for uses of `.append()`, `.after()`, and other DOM manipulation functions. Check if the arguments are strings built from user data.
* [ ] Convert them to safe versions.

**Comment by jamesnakagawa** [comment]
I searched all `.js` and `.ts` files in project directories for any use of `.before()`, `.after()`, `prepend()`, `append()`, `html()`, or `innerHTML` and reviewed each case individually. Even in places variable code was provided by the server API, I converted it to a safe mode.
