### ISSUE TITLE
Incorrect reporting of a failed step in a pipeline

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#622]
To reproduce this error, do the following:
a) manage.py reset --load=demo
b) manage.py runserver   (and the fleet...)
c) in Kive, under Users/runs , you can see that the MiCallDemo has completed successfully.
d) switch on administrator mode, and remove the MicalDemo run data.
e) go to Users/Analysis, and set up a new MiCallDemo run with the input data provided and start the run.
f) The pipeline will fail on step 6 (coverage plots), however, when looking at the Details of the run, there is no step 6 listed.
Looking into the kivemediaroot directory Logs, step 6 did run with a warning on stderr.

## Update: fixes required ##
* [x] regenerate demo fixture
* [x] display integrity violation for step that failed setup
* [x] delete logs when deleting a run

**Comment by donkirkby** [comment]
Here's what seems to have happened:

1. The script for step 6 got changed in the `FixtureFiles` folder, so it no longer matched the MD5 in `demo.json`.
2. When rerunning the pipeline, there was an integrity violation while setting up the sandbox, so the step didn't run.
3. The log file you saw was actually from the original run that got deleted. Logs aren't deleted when you delete a run (a bug).

I've added a task list to the bug description to handle these three problems.
