### ISSUE TITLE
Adding multiple datasets from archive crashes Kive

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#623]
It is easy to crash Kive when adding mutliple datasets from archive. E.g. when an nonexistent
archive is provided.

**Comment by donkirkby** [comment]
@wrpscott will fill out more details for reproducing.

**Comment by wrpscott** [comment]
I can indeed reproduce this error. I see a ValidationError at /datasets_bulk.html . Will look  into this.

**Comment by wrpscott** [comment]
The problem occurs when a non-zip file is selected. Can catch this, but also try and make the difference between add bulk data and bulk data from archive clearer to the user.
