### ISSUE TITLE
method_new: unable to select permissions field

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#626]
When creating a new method family, selecting the permissions for it does not work. Possibly related to javascript issues, however, other javascript elements on the page do work.

**Comment by jamesnakagawa** [comment]
Seems to be that cr_id was not declared. I wonder how that happened...

**Comment by jamesnakagawa** [comment]
Looks like this was caused by inserting "use strict". `cr_id` has never been declared so was previously attached to the global object.
