### ISSUE TITLE
Roadmap to "streamlined pipeline creation workflow"

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#629]
Since this release is called "streamlined pipeline creation workflow", I thought I would plan out the steps to actually get to that specific goal. This is an issue for discussion, but once I feel we've agreed on the roadmap here, I'll split this into individual tasks. I'll also provide some mockups so that we get an idea of what it will look like.

The way I see it, you should be able to:

* Define new CDTs _while_ defining a method
* Upload new CodeResources _while_ defining a method
* Define a new method and all of the above _inside_ of the pipeline creation interface
* Ask to run a pipeline from that pipeline's editing interface

The first thought the user should have is "I have this script or scripts, I want to make a pipeline out of them." It would be nice if we could thrust them into the canvas interface as soon as possible and have most operations be carried out there.

I think this is the primary thing we want to consider, is if the workflow has the same order as the user's thought process.

**Comment by donkirkby** [comment]
What do you all think of this possible feature? We could distinguish editing from revising. If a pipeline, method, or code resource has been used in a run, it can only be revised with a new version. If it hasn't been used, then it could be edited in place. Maybe it can always be edited, but you can only change the name and description if it's already been used. I know we've talked about this before, but I couldn't find an issue. Closely related issues are #504, #505, and #506.

Another related feature: browsing from dataset to input/output runs to pipeline to code.

**Comment by jamesnakagawa** [comment]
That would be useful. We may want to introduce a label to explain this behaviour to our users. "Canonical" comes to mind? On each feature's description page, it can have a "Canonical" or "Non-canonical" label with a short info box explaining what and why. We could also consider listing the runs it has been used in (if there are few).

What do you mean by input/output runs? Same as 'runs'?

**Comment by donkirkby** [comment]
By input/output runs, I just meant runs that produced the selected dataset as an output or used it as an input.

I'm not sure that "Canonical" would be clear to users. Perhaps "draft" or "new" for features that haven't been used in a run yet, and "used" or "in use" for ones that have been used. "New" and "Used" are fairly clear opposites from a retail context.

**Comment by jamesnakagawa** [comment]
"New" is also the opposite of "old", though.

* Used / unused?
* Deployed / not deployed?
* Employed / unemployed?

We should be aware that we already have Published/Unpublished for pipelines, so it should somewhat make sense in relation to that, too

**Comment by donkirkby** [comment]
I'm happy with used/unused to indicate whether changes can still be made to a version, and published/unpublished to indicate whether regular users can see a version.

**Comment by rhliang** [comment]
I mildly prefer "Deployed" and "Undeployed" to used/unused, or perhaps "Live" and "Staging".

On the topic of published/unpublished, I think it would make sense for something that has been marked as published to be un-editable (beside the trivial stuff).  A developer could unpublish something but only if it was unused/not deployed/staging.

**Comment by jamesnakagawa** [comment]
I just realized we already have issues for much of this - closing.
See #504, #505, #506, and #631 .
