### ISSUE TITLE
Allow edits to Pipelines, Methods, and CodeResources when they have never been used

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#631]
Re: #629, this is something we're interested in.

Current behaviour does not allow edits, only revisions.

Discussed terminology for describing these fixtures are "Used/Unused", "Deployed/Not yet deployed". This distinction is only slightly related to a pipeline's "Published" status.

**Comment by donkirkby** [comment]
I'll skip the gif this time, but "published/unpublished" is currently unrelated to whether a pipeline has been run. It just affects whether regular users can see it in the analysis list. The intention was that a developer could work on a new version of a pipeline without letting users see it and be frightened by its unfinished horror.

One thing we have to be careful of: a user could launch a pipeline while the developer is working on it.

**Comment by jamesnakagawa** [comment]
Thanks, edited
