### ISSUE TITLE
Call to non-blocking probe_for_finished_worker

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#633]
Comment in [code] says 'blocking call', whereas `MPI,Iprobe()`  is not blocking. Is this correct?

[code]: https://github.com/cfe-lab/Kive/blob/v0.8.5/kive/fleet/workers.py#L421

**Comment by rhliang** [comment]
Yeah, looks like a mistake.  I suspect that at some point I used regular `probe` but changed it later.  Looks like we're lucky that this hasn't bit us yet!

**Comment by donkirkby** [comment]
All of that MPI code has been replaced by Slurm code, so I'm closing the issue.
