### ISSUE TITLE
Kive should handle pipeline priorities

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#634]
With the upcoming transition of Kive to use slurm, which can handle job priorities, Kive now has to determine the priority when calculating something.

**Comment by rhliang** [comment]
Right, we should talk about the policy for this.  I imagine that we will simply default everything to a "standard" priority, while allowing for different levels to be selected when creating the run.  As a first pass, we should at least have a "Clinical" priority that is higher than standard, but perhaps it would make sense to allow administrators to define their own priority levels?

**Comment by rhliang** [comment]
Let's define three (?) levels of priority in `settings.py` that can be chosen at run time by the user starting a run.  Administrators will be given the option to change said priority to any integer value after the fact if necessary.  Let's see if this gets done before v0.9 -- won't be terrible if it gets punted to v0.10.

**Comment by rhliang** [comment]
Closed in the changes leading to v0.10.
