### ISSUE TITLE
centos5 reaches end-of-life on 31. March 2017

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#635]
Plans for transitioning Kive from centos5 for production should be made soon.
Would a move to using docker on centos7 or ubuntu core make sense?
There are no rpm packages for slurm under centos. However, slurm has been compiled from source and installed successfully in docker images of centos versions 5, 6 and 7.

**Comment by rhliang** [comment]
Plan is to migrate everything over to Octomore before upgrading.  This will probably include moving several of the compute nodes that are currently part of Bulbasaur over to Octomore.  Octomore is currently on CentOS 6 and a newer version of Scyld ClusterWare, which should last us a good long while.

After that we can attempt to upgrade Bulbasaur (which will now be the development machine) to a newer version -- perhaps without support from Penguin Computing?

**Comment by wrpscott** [comment]
As of 2016-12-22, awaiting a quote from Penguin Computing for new versions of Scyld.

**Comment by ArtPoon** [comment]
Keep on them about it.  In my experience they often lose track of quote and purchase requests.

**Comment by wrpscott** [comment]
Both octomore and bulbasaur are now running centos7.
