### ISSUE TITLE
Improve Runs page loading behaviour

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#638]
Some minor foibles of the Runs page:

* A click on the Stop link can be missed, likely due to concurrency between a refresh event and a click event.
* Sometimes when stopping a Run, after pressing "OK" in the dialogue box, the table blanks out briefly before reloading (correctly).
* Upon adding a search, the table first displays a message saying "No results found", which is misleading as it's simply still searching.

**Comment by donkirkby** [comment]
Issue will go away when we remove the old pipeline features.
