### ISSUE TITLE
Lookup: searching for a file crashes Kive

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#639]
Dropping a file into the search area leads to a Kive server crash:
  File "/home/walter/Kive/kive/librarian/views.py", line 533, in dataset_lookup
    if d["run_id"] == run.id and d["dataset"].id == input.dataset.id:
KeyError: 'run_id'

**Comment by donkirkby** [comment]
Is this related to #624?

**Comment by wrpscott** [comment]
This issue was indeed resolved with #624 and closed in 3613ac6
