### ISSUE TITLE
Failed CustomConstraintLogs are not handled

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#643]
Just noticing that when custom constraints are checked, the code more or less assumes that the method had no problems during execution.  Need to add some handling for the case where the code fails for some reason.

**Comment by donkirkby** [comment]
I know we don't do an integrity check after a failed method, so maybe we should skip the custom constraints. For example, it's likely that a failed method would leave an output blank. That would then fail the constraint on the column names.

If we do that, we should probably do something to prevent these unchecked datasets from being used as inputs. Maybe an `is_validated` field?

**Comment by rhliang** [comment]
I agree the thing to do is to leave the Dataset without a complete content check.

There's already some code that prevents such datasets from being used, I think -- Datasets have a `usable_in_run` method that basically checks this.

**Comment by rhliang** [comment]
Been working on this in my branch; will close when tested.  This will not go into v0.9, but will go into the first proper Slurm version.

**Comment by rhliang** [comment]
As of #652, this issue is now irrelevant, and will be closed when the Slurm branch merges into master.
