### ISSUE TITLE
Datasets upload: If CDT is wrong, process fails silently

### ISSUE THREAD

**Issue by jamesnakagawa** [cfe-lab/Kive#644]
Steps to reproduce:

1. Navigate to `/datasets_add_archive`
2. Select a ZIP file.
3. Select a CDT which does not match.
4. Press submit.

Expected: UI to display an error.
Actual: A metadata table is displayed with empty fields (but the right _number_ of rows) and the status is erroneously displayed as "success". Errors are, however, displayed by Django in the console.

**Comment by wrpscott** [comment]
What would happen if we want to upload a zipfile which contains different kinds of CDT?
Shouldn't the choice of CDT be for an individual files ?
The archive upload code has changed quite a bit since the last commit, but this issue is still valid.

**Comment by donkirkby** [comment]
I think restricting it to a single CDT is reasonable. Uploading multiple files in a zip file is just a convenience feature. If a user really needs to upload 100 files with 20 different CDT's, they can either upload 20 different zip files, or they can script the uploads using the API.

**Comment by jamesnakagawa** [comment]
I agree with @donkirkby, I think that would be reasonable feature for the future, but for now we just want it to work the way it's supposed to.
