### ISSUE TITLE
Removing a Run can lead to CSRF Failed: CSRF token missing or incorrect error

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#646]
Removing a run as administrator fails.

**Comment by jamesnakagawa** [comment]
@wrpscott, I recently messed with this file/commit which is related to CSRF:
f6913623d054bcb8229966900cfb4bc3e91562bf /kive/portal/static/portal/noxss.js
Should only have affected jQuery AJAX requests.

**Comment by donkirkby** [comment]
It's working for me, @wrpscott. Have you run `npm build` to make sure you have the latest Javascript?

**Comment by wrpscott** [comment]
Cannot reproduce the problem, Agreed might not have rebuilt properly.
