### ISSUE TITLE
Runs page is getting slow (again)

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#649]
Improve performance before v0.9 release.

**Comment by donkirkby** [comment]
Some strategies to consider:
* `AccessControl.filter_by_user()` uses a distinct clause. My tests show it's 4 to 5 times faster with a subquery when querying datasets in production.
* Postgres [vacuum] command - I didn't notice any improvement in my development database or Octomore when I ran this, but the documentation recommends running it regularly.
* Use Postgres explain plan to find problems with the slow queries, like missing indexes.

[vacuum]: https://www.postgresql.org/docs/9.1/static/sql-vacuum.html

**Comment by donkirkby** [comment]
Strategies to find slow queries:

* Look at `connection.queries` and search for [slow] or [frequent] queries.
* Once you find a problem query, put a conditional breakpoint in the database [execute] method, then look at the call stack to see where the query is coming from.

[slow]: https://github.com/cfe-lab/Kive/blob/969855e2d0b1ade608c9f0fd857af800efd959b4/kive/archive/management/commands/check_complete_runs.py#L85
[frequent]: https://github.com/cfe-lab/Kive/blob/969855e2d0b1ade608c9f0fd857af800efd959b4/kive/archive/management/commands/check_complete_runs.py#L97
[execute]: https://github.com/django/django/blob/1.9.2/django/db/backends/utils.py#L84
