### ISSUE TITLE
Allow StashedWhileTesting path to be specified in settings

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#650]
I was having problems with tests taking an extremely long time to start running, and tracked the problem down to the `kive.tests.install_fixture_files` method.  Because I'm running Kive on a virtual machine, with the Kive source folder being mounted as a "shared" folder, the problem was that moving the contents of the `CodeResources`, `Logs`, etc. directories to the `StashedWhileTesting` subdirectory of the source folder was taking a very long time (due to the foibles of VirtualBox's shared folder support).  Changing the path solved this problem.

**Comment by donkirkby** [comment]
I changed this behaviour in 5f4d8e878d362a7ef02844a679ccb4fc5b4fe5cf. It now creates a new `MEDIA_ROOT` folder during testing as a subfolder of the main one. You could cherry pick it to the Slurm branch, if you want to.

I'm closing this issue, but feel free to reopen it if that change doesn't solve your problem.

**Comment by rhliang** [comment]
Yes, this is perfect, thanks!
