### ISSUE TITLE
Bookkeeping step should only be started after the Foreman completes the ExecLog for the driver

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#651]
Sifting through execution tests, I'm noticing a small problem.  Currently, Slurm execution is broken into three chunks:

* setup
* driver
* bookkeeping

All of these are submitted at the same time, with explicit dependencies ensuring that they run one after another.

However, there's a fourth component to this, which is that after the driver has run, the Foreman completes its ExecLog with the output log and error log.  I thought that this could happen concurrently with the bookkeeping part of the execution, but am now seeing that this could possibly cause some problems.

As such, I think it would be better to modify the way Kive runs jobs, so that setup and driver are started together, and then bookkeeping is only started after the driver has finished and the Foreman has had a chance to complete its ExecLog.

**Comment by wrpscott** [comment]
Richard!
no problem, in fact two slurm jobs are better than three...
I am almost finished with the slurm tests and will push my stuff 
shortly. Then you can take it away!

kind regards,
Scotty

**Comment by wrpscott** [comment]
Hello RIchard

Okay, ( I was thinking that the first job doesn't do that much, and 
could be merged in with the second.)

Okay, I have now pushed. Minor changes to Manager, and you should be 
able to use DummySlurm as well as
normal slurm for execution now.
I won't touch the Kive code until I hear back from you. In the mean 
time, I will look into how priorities are handled
by slurm.

kind regards,
Scotty

**Comment by rhliang** [comment]
This is closed in the Slurm branch.
