### ISSUE TITLE
Remove custom constraints

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#652]
Discovered that having them run using Slurm is problematic because the time they'll be running is usually during RunCable execution or during a RunStep's bookkeeping stage, which are themselves Slurm tasks.

Rather than fix this further, @donkirkby suggested that we just get rid of the custom constraints altogether.  It's not built into the UI anyway, and hasn't been demonstrated to be that desired of a feature.

**Comment by donkirkby** [comment]
If developers wanted a custom constraint, they could write a method that copies a file and checks its contents.
