### ISSUE TITLE
Modify DummySlurmScheduler to run step setup, step bookkeeping, and cable execution in line

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#655]
I already discussed this with @donkirkby and @wrpscott.  We'd like `DummySlurmScheduler` to perform these tasks in line (i.e. in the Manager) without farming them out to subprocess.  This will enable us to better test some of the key components of the execution code: `Sandbox.step_execution_setup`, `Sandbox.step_execution_bookkeeping`, and `Sandbox.finish_cable`.

The plan is for Scotty to make the required fixes.  I've dummied up some methods in `DummySlurmScheduler` to perform the tasks in line, and am leaving it to Scotty to fill in the details of how to properly notify the `masterproc` of `DummySlurmScheduler` so that we're able to fetch accounting info on these tasks.  I've tried to leave lots of comments in the code to help him with the nitty gritty details.

**Comment by wrpscott** [comment]
closed by  4590f32. All kive tests pass.
