### ISSUE TITLE
Raw datasets displayed without line breaks

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#657]
If you view a raw dataset, the contents are displayed with normalized whitespace, the line breaks have been removed.

It looks like the problem is this section of `portal/style.css`, added in commit 81d95e284f8a34db0f1ab35605e22eb3bb7d3ad3:

    pre {
        word-break: break-all;
        white-space: normal;
    }

@jamesnakagawa, do you remember why that was needed? Will anything bad happen if we just remove it?

**Comment by jamesnakagawa** [comment]
I remember making this change so that ultra-long strings of text would wrap even if they were all word characters (like `CGATTGATCGATGTGGC...`). I think changing the value of `white-space` to `pre-wrap` should preserve line breaks while still allowing the lines to wrap.
