### ISSUE TITLE
Runs cancelled by the system still appear as "In Progress" on the View Run page

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#671]
Had another run fail due to issue #668 and noticed a small issue on the UI.

![inprogress](https://cloud.githubusercontent.com/assets/5862525/24009393/0f8d3798-0a32-11e7-8c7b-cb247d2c033e.png)

In this run, the output cable leading to the `insert` output failed, and I confirmed this by looking into the run's sandbox.  However, note that the run status still shows "In Progress" despite having been stopped:

![inprogressstatus](https://cloud.githubusercontent.com/assets/5862525/24009561/993b17bc-0a32-11e7-87c7-6eb08c275020.png)

and having RunState "Failed".

**Comment by wrpscott** [comment]
Will test this by forcing a job cancel (moving a required file) of an executing run, then looking for the reported job state.

**Comment by wrpscott** [comment]
This bug is directly related to #667. Taking on both issues at the same time as they both relate to how *failed cables*  are detected and reported.
