### ISSUE TITLE
Add widget to select which queue a run gets assigned to when it's started

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#672]
Continuing on from #508, the backend is now capable of this, but we have no means in the UI to set this when starting a job.

**Comment by donkirkby** [comment]
Consider other Slurm options that could be useful to configure on a run or on a method. For example, the `--mem` option specifies how much memory to allocate for a Slurm task, and we could define that on a method. Do we need to override it on a run if it gets cancelled for excessive memory usage, or is that a sign of a broken pipeline?
