### ISSUE TITLE
Stress test Kive with different NFS mount options

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#682]
This is an ongoing attempt to understand the issues we are having with file writing on the cluster.
As part of operation Sharknado I, we will install an operational Kive on the test cluster. Once this is done:

- disable defensive file writing code and run stress tests
- remount the cluster NFS mounts with file locking enabled
- write a small, distributed program to test file locking behaviour
- rerun stress tests

Hopefully, we will have learned something by the end of these tests.

**Comment by donkirkby** [comment]
Last night, we ran the first test without changing any file handling code or Slurm options. We were hoping to see the Slurm node failures described in #569.

Between 4:30pm and 9:00am, 250 jobs completed, including 8 failures. Here's a list of the run ids and why they failed.

* 70 19:47 oomkiller killed aln2counts on n2
* 99 20:19 Python failed to launch bowtie2 from remap on n2
* 69 20:35 oomkiller killed remap on n2
* 59 21:31 oomkiller killed remap on n2
* 109 21:43 oomkiller killed remap on n2
* 58 22:51-22:53 oomkiller killed bowtie2 under prelim_map on n3
* 161 05:22 oomkiller killed bowtie2 under prelim_map on n2
* 162 07:09-07:11 oomkiller killed bowtie2 under prelim_map on n2

**Comment by donkirkby** [comment]
We have configured Slurm to use consumable resources for memory and CPU's, and we haven't seen any oomkiller failures. However, the Micall pipeline keeps exceeding the memory we allocate for it: first 3GB, then 6GB. We need to fix the memory usage in the pipeline, or big samples will always fail. The five failures last night had compressed FASTQ files of 800MB, 500MB, 500MB, 550MB, and 600MB. They all came from the 26 Feb 2016 run. Interestingly, the failures happened in different steps: prelim_map, aln2counts x 2, and sam2aln x 2. One of the failures happened on the head node, so swap space won't always solve the memory problem.

**Comment by donkirkby** [comment]
As a workaround, we configured Kive to request 20GB for every driver script, and that worked. The most memory used was just over 10GB for the 800MB sample's aln2counts step. The longest elapsed time was 5h50m for the same sample's remap step. However, it used less than 1GB of memory.

**Comment by donkirkby** [comment]
Through some combination of defensive copy code, switching to Slurm, replacing the network switch, and upgrading the operating system, we haven't seen these file copying problems in months. I'm closing this issue, and we can reopen it if the problems come back.
