### ISSUE TITLE
Slurm moving jobs between nodes

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#687]
After rebuilding the cluster on CentOS 7, we found that some jobs were appearing with NODE_FAIL state, then getting restarted by Slurm on another node. More details are recorded on issue #569.

The plan is to use `--no-kill --no-requeue` to stop Slurm from doing this. It would also be helpful to figure out why the head node loses track of the jobs and requeues them.

To see if the problem is still happening, use this:
```
[don@bulbasaur ~]$ sudo grep "missing from node" /var/log/slurm/slurmctld.log 
...many entries...
[2017-05-15T15:29:04.557] Batch JobId=42746 missing from node 0 (not found BatchStartTime after startup), Requeuing job
```

These are also helpful:
```
[don@bulbasaur ~]$ sacct -ukivefleet -o jobname%50,jobid,state,exitcode,start,end,elapsed,maxrss,nodelist -S2017-05-15 -snf
                                           JobName        JobID      State ExitCode               Start                 End    Elapsed     MaxRSS        NodeList 
-------------------------------------------------- ------------ ---------- -------- ------------------- ------------------- ---------- ---------- --------------- 
                                run774\_cable26613 40153         NODE_FAIL      0:0 2017-05-15T14:15:39 2017-05-15T14:15:41   00:00:02                         n2 
             r859s\(3\,\)driver\[prelim\_map\.py\] 42746         NODE_FAIL      1:0 2017-05-15T15:28:34 2017-05-15T15:29:04   00:00:30                         n0 
[don@bulbasaur ~]$ sacct -ukivefleet -o jobname%50,jobid,state,exitcode,start,end,elapsed,maxrss,nodelist --duplicates -j42746
                                           JobName        JobID      State ExitCode               Start                 End    Elapsed     MaxRSS        NodeList 
-------------------------------------------------- ------------ ---------- -------- ------------------- ------------------- ---------- ---------- --------------- 
             r859s\(3\,\)driver\[prelim\_map\.py\] 42746         NODE_FAIL      1:0 2017-05-15T15:28:34 2017-05-15T15:29:04   00:00:30                         n0 
             r859s\(3\,\)driver\[prelim\_map\.py\] 42746         COMPLETED      0:0 2017-05-15T15:32:43 2017-05-15T15:48:37   00:15:54                         n1 
                                             batch 42746.batch   COMPLETED      0:0 2017-05-15T15:32:43 2017-05-15T15:48:37   00:15:54   2548776K              n1 
```

**Comment by rhliang** [comment]
I'll add that job 40153 in the above printouts didn't even have an error message in the log.  The log simply says something about how the job is being moved at "user/system request".  It wasn't any of us, so it must have been the system -- either Slurm itself or (and I can't imagine how it would be the case, but who knows) Kive did it somehow.

```
[2017-05-15T14:15:41.511] job_complete: JobID=40153 State=0x1 NodeCnt=1 WEXITSTATUS 0
[2017-05-15T14:15:41.511] job_complete: requeue JobID=40153 State=0x8000 NodeCnt=1 per user/system request
[2017-05-15T14:15:41.511] job_complete: JobID=40153 State=0x8000 NodeCnt=1 done
[2017-05-15T14:15:41.513] Requeuing JobID=40153 State=0x0 NodeCnt=0
```

**Comment by donkirkby** [comment]
We ran a bunch of samples through Bulbasaur with the `--no-kill --no-requeue` settings, and it didn't cause any problems. That doesn't prove that this will solve the problem, but at least it didn't make anything worse.

**Comment by donkirkby** [comment]
Since we changed the Kive configuration, we've run three MiSeq batches without any failed samples. However, I found one failure that looks like job 40153 described above. The sample still succeeded in Kive, but we may have just been lucky that Kive didn't notice it while it was in the NODE_FAIL state.

Here's what we know about the new failure:

```
[don@octomore ~]$ sacct -ukivefleet -snf -sca -sf -o jobname%50,jobid,state,exitcode,start,end,elapsed,maxrss,nodelist -S 2017-05-18T17:00
                                           JobName        JobID      State ExitCode               Start                 End    Elapsed     MaxRSS        NodeList 
-------------------------------------------------- ------------ ---------- -------- ------------------- ------------------- ---------- ---------- --------------- 
                            r252847s\(1\,\)\_setup 675989        NODE_FAIL      0:0 2017-05-21T15:17:08 2017-05-21T15:17:10   00:00:02                         n0 

[don@octomore ~]$ sacct -ukivefleet  -o jobname%50,jobid,state,exitcode,submit,start,end,elapsed,maxrss,nodelist --duplicates -j675989
                                           JobName        JobID      State ExitCode              Submit               Start                 End    Elapsed     MaxRSS        NodeList 
-------------------------------------------------- ------------ ---------- -------- ------------------- ------------------- ------------------- ---------- ---------- --------------- 
                            r252847s\(1\,\)\_setup 675989        NODE_FAIL      0:0 2017-05-21T14:47:23 2017-05-21T15:17:08 2017-05-21T15:17:10   00:00:02                         n0 
                            r252847s\(1\,\)\_setup 675989        COMPLETED      0:0 2017-05-21T15:17:10 2017-05-21T15:25:24 2017-05-21T15:39:23   00:13:59                         n0 
                                             batch 675989.batch  COMPLETED      0:0 2017-05-21T15:25:24 2017-05-21T15:25:24 2017-05-21T15:39:23   00:13:59     45008K              n0 

[don@octomore ~]$ sudo grep 675989 /var/log/slurm/slurmctld.log
[sudo] password for don: 
[2017-05-21T14:47:23.764] _slurm_rpc_submit_batch_job JobId=675989 usec=318
[2017-05-21T15:17:08.559] sched: Allocate JobID=675989 NodeList=n0 #CPUs=1 Partition=kive-slow
[2017-05-21T15:17:10.849] job_complete: JobID=675989 State=0x1 NodeCnt=1 WEXITSTATUS 0
[2017-05-21T15:17:10.849] job_complete: requeue JobID=675989 State=0x8000 NodeCnt=1 per user/system request
[2017-05-21T15:17:10.849] job_complete: JobID=675989 State=0x8000 NodeCnt=1 done
[2017-05-21T15:17:10.851] Requeuing JobID=675989 State=0x0 NodeCnt=0
[2017-05-21T15:25:24.721] sched: Allocate JobID=675989 NodeList=n0 #CPUs=1 Partition=kive-slow
[2017-05-21T15:39:23.128] job_complete: JobID=675989 State=0x1 NodeCnt=1 WEXITSTATUS 0
[2017-05-21T15:39:23.128] job_complete: JobID=675989 State=0x8003 NodeCnt=1 done
```

According to the [Slurm source code][src], state 0x8000 means `JOB_PENDING` and `JOB_COMPLETING`, while 0x8003 means `JOB_COMPLETE` and `JOB_COMPLETING`.

From looking at this [bug report], my guess is that Kive wrote a wrapper script for Slurm, but there was an NFS failure when Slurm tried to read it during the launch. That made Slurm requeue the job, and NFS worked the second time. It sounds like Slurm makes a copy of the launch script, so that copy might fail even if we check that the original write of the script succeeded.

The good news is that the sample succeeded in Kive. I suggest we leave this issue open until we see what happens during the next few MiSeq batches.

[src]: https://github.com/SchedMD/slurm/blob/c7d35eb97e6cfee7257f591901e1837d89d6a54a/slurm/slurm.h.in#L204
[bug report]: https://bugs.schedmd.com/show_bug.cgi?id=2879

**Comment by rhliang** [comment]
Interesting that it requeued even with `--no-requeue` selected.

**Comment by donkirkby** [comment]
It's just a guess, but perhaps it will still requeue if it fails to even launch the job. However, that doesn't seem to agree with the [docs] for `--no-requeue`.

>Specifies that the batch job should never be requeued under any circumstances.

[docs]: https://slurm.schedmd.com/sbatch.html

**Comment by donkirkby** [comment]
On Thursday, May 25, we noticed that the Kive configuration was incorrect, and the jobs were being submitted to use all the memory available on a node. This meant that only one job was running at a time on each node. We corrected the configuration on both Octomore and Bulbasaur, and Bulbasaur has successfully processed the last three months of data.

However, Octomore failed both batches that ran over the weekend. I see similar messages about "missing from node" in the `slurmctld.log` file, so it looks like the errors still occurred, but the jobs didn't get requeued.

Next thing to try: increasing [SlurmdTimeout]?

>The configuration parameter SlurmdTimeout determines the interval at which slurmctld routinely communicates with slurmd. Communications occur at half the SlurmdTimeout value. The purpose of this is to determine when a compute node fails and thus should not be allocated work. Longer intervals decrease system noise on compute nodes (we do synchronize these requests across the cluster, but there will be some impact upon applications). For really large clusters, SlurmdTimeout values of 120 seconds or more are reasonable.

[SlurmdTimeout]: https://slurm.schedmd.com/big_sys.html

**Comment by donkirkby** [comment]
I also saw some errors about overheated CPU's in `/var/log/messages`, so it might be worth testing with [Prime95] and checking the cooling systems on the compute nodes.

[Prime95]: https://en.wikipedia.org/wiki/Prime95#Use_for_stress_testing

**Comment by donkirkby** [comment]
@rhliang has begun testing with Prime95 on Octomore, and we've had another failed run on Tuesday evening. 7 tasks were left in the NODE_FAIL state between 22:25 and 23:32. All 7 were on n0 and n1. At least one of the tasks seemed to have successfully completed the task, even though Slurm had lost track of it. Two others didn't seem to have started, so perhaps the failure happened before the process actually launched from Slurm.

**Comment by donkirkby** [comment]
We've seen fewer NODE_FAIL errors in the last month, and all but one have happened during the job launch. In that scenario, Slurm requeues the launch, and the state switches from NODE_FAIL to PENDING again.

Here's the plan:
1. Make Kive wait 5 minutes before giving up on a job that's in the NODE_FAIL state. Put out a patch release with that change.
2. If we can live with the remaining NODE_FAIL rate, close this issue.
3. Otherwise, make the Kive setup, bookkeeping, and cable jobs use database transactions to protect themselves against being run multiple times.
4. Make the wrapper script include the SLURM_RESTART_COUNT environment variable in the output file names. That will let multiple instances of the job run in parallel if it gets requeued.
5. Go back to allowing requeuing.

**Comment by rhliang** [comment]
I'll also add that we should change the way Slurm writes the stdout and stderr logs so that it appends rather than truncates the log files.  This way if a job is requeued on the same node then it won't wipe the earlier log output.

**Comment by rhliang** [comment]
Are we sure that we never see `NODE_FAIL` on jobs that have been running for a little while and then

**Comment by rhliang** [comment]
Sorry, accidentally clicked on "close and comment" while I was trying to delete a half-formed thought.

... carry on.

**Comment by wrpscott** [comment]
The current code on Bulby now has the code in the Foreman to handle NODE_FAIL states. Repeating the test in which a NODE_FAIL state is induced by iptables, the Foreman detects and logs the NODE_FAIL state, and then recovers when the connection to the compute node is reestablished. The run completes successfully.
