### ISSUE TITLE
Runs manually stopped from the UI lose their `stopped_by` value

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#688]
@donkirkby and I noticed this the last couple of days.  When going down the list of active runs to stop them, the "Stop" button is replaced with "(Stopped by user [username])" as it always has.  After the run is actually stopped, though, this text sometimes disappears.  I looked at one of the runs in the Django shell and it didn't have a value set for `stopped_by`, which is the field storing the username of the user who stopped the run.

Possibly the Foreman is calling `save()` on a local copy of the run which has `stopped_by = None`?

**Comment by donkirkby** [comment]
This is no longer a problem in container runs, and we can live with it until we convert the old pipelines to new containers. I'm closing this as won't fix.
