### ISSUE TITLE
Downgrade squeue error on a finished Slurm job from a warning message to a debug or info message

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#695]
Don noticed some messages like the following in `kive_fleet.log` on the test cluster:

```
2017-06-20 12:37:47[WARNING]fleet.slurmlib._call_to_dict(): squeue returned an error code '1'

Command list:
['squeue', '--format=%i %j %P %V', '-p', 'kive-slow,kive-medium,kive-clinical', '-j', '315182']

Output:


stderr:
slurm_load_jobs error: Invalid job id specified
Traceback (most recent call last):
  File "/usr/local/share/Kive/kive/fleet/slurmlib.py", line 496, in _call_to_dict
    out_str = sp.check_output(cmd_lst, stderr=f)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['squeue', '--format=%i %j %P %V', '-p', 'kive-slow,kive-medium,kive-clinical', '-j', '315182']' returned non-zero exit status 1
```

The manager continued to run without issue, though.  A quick peek through the code shows that this is expected behaviour: the job in question was already finished, so `squeue` fails to return any information about it, and `sacct` is used to extract more detailed information afterwards.  Instead of logging this at the `WARNING` level, let's change it to be at the `DEBUG` or `INFO` level.

**Comment by donkirkby** [comment]
Because of the retry logic added in 98802740379ca6c65dc8dca1b3044d1794baff49 for #687, this is no longer an issue. Closing.
