### ISSUE TITLE
Don't reuse failed steps in a run

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#696]
Because some failures are caused by external problems like memory or network access, I don't think we should reuse failures. I can live with it if we sometimes don't reuse a success that we could have.

**Comment by rhliang** [comment]
Suppose we've run it two times, the first time it was successful, and the second time it was unsuccessful (this could happen if the output had been purged and the second time it encountered a system failure).  Do we fall back on the good one in case the outputs aren't necessary, or do we force it to rerun outright?

**Comment by donkirkby** [comment]
If the outputs aren't necessary, I would fall back on the good one.
