### ISSUE TITLE
Evaluate Dugong tools for Docker

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#714]
The [Dugong] project seems to make it easier to set up Docker images with bioinformatics tools installed. See if it would be useful for pipeline developers, and if it could be integrated into Kive.

[Dugong]: https://dugongbioinformatics.github.io/

**Comment by rhliang** [comment]
Sounded interesting at first, but from the documents it seems the main appeal of the platform is that it includes XFCE4 and lots of GUI-based tools (they intend for you to log in using VNC primarily, I think).

The packages it espouses as promoting reproducibility are Jupyter Notebook, `script`, and `scriptreplay`.  I've always known Jupyter to be mainly a web-based thing, but they do raise a good point that it does let you see a pretty thorough history of commands and what the commands produced.  If there's a command-line-based version of this (would this just be IPython?) then for small scale analyses this could be useful to include in our eventual default Docker container.

**Comment by donkirkby** [comment]
Closing, because we stopped using docker, and the tools didn't look that interesting.
