### ISSUE TITLE
Interrupted docker wrapper leaves volume behind

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#717]
If you launch the `docker_wrap.py` script, and then press <kbd>Ctrl</kbd>+<kbd>C</kbd>, the wrapper script aborts without killing the docker process. That makes the `docker volume rm` fail.

It looks like the `docker_wrap.py --run` process also continues to run when the parent process is interrupted. For example, cancelling the slurm task doesn't stop the actual job process.

* [x] clean up volume and container
* [x] stop running child process

```
$ docker_wrap.py alpine --sudo -- sandbox1 sleep 30
Session: don_sandbox1
Input files:

Launching.
^CTraceback (most recent call last):
  File "/usr/local/bin/docker_wrap.py", line 252, in <module>
    main()
  File "/usr/local/bin/docker_wrap.py", line 244, in main
    handle_run(args)
  File "/usr/local/bin/docker_wrap.py", line 223, in handle_run
    check_call(docker_args)
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Error response from daemon: unable to remove volume: remove don_sandbox1: volume is in use - [76ba81e5772f5ee9cc68831ac854b3482bd08757f98a16892760e2e1e0d99f46]
Traceback (most recent call last):
  File "/usr/local/bin/docker_wrap.py", line 252, in <module>
    main()
  File "/usr/local/bin/docker_wrap.py", line 246, in main
    handle_write(args)
  File "/usr/local/bin/docker_wrap.py", line 229, in handle_write
    clean_up(session)
  File "/usr/local/bin/docker_wrap.py", line 236, in clean_up
    check_output(['docker', 'volume', 'rm', session])
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'volume', 'rm', 'don_sandbox1']' returned non-zero exit status 1

Outputs:
Traceback (most recent call last):
  File "/usr/local/bin/docker_wrap.py", line 252, in <module>
    main()
  File "/usr/local/bin/docker_wrap.py", line 248, in main
    handle_launch(args)
  File "/usr/local/bin/docker_wrap.py", line 135, in handle_launch
    raise CalledProcessError(exporter.returncode, export_args)
subprocess.CalledProcessError: Command '['sudo', '/usr/local/bin/docker_wrap.py', '--write', 'alpine', 'sandbox1']' returned non-zero exit status 1
$ 
```

## Final clean up ##
* [x] test interrupt during write
* [x] nested try / finally / except
* [x] switch constant to command line and delete unused
* [x] show default command line args
* [x] dictConfig of logging, `-q` sets to warn, and `-v` sets to debug

**Comment by rhliang** [comment]
I've been trying to catch `KeyboardInterrupt` and having it pass on a `SIGINT` to the running process, but it seems to have the same problem where the container doesn't get killed until later.  I'm going to try using `docker stop` instead.

**Comment by donkirkby** [comment]
Try doing a `docker run --rm ...` with a sleep command, and then killing that process with `SIGINT`. It's possible that the `--rm` doesn't happen in that situation. `docker stop` might work.

**Comment by rhliang** [comment]
For posterity, here's what I found.  In one tab, I ran:

```
sudo docker run --rm --name test_container_to_kill alpine sleep 120
```

In another tab:
```
(Kive) rliang@Zoidberg-VirtualBox:~/src/copperfish/kive$ ps aux | grep docker
root      1919  0.0  0.0  56844  3964 pts/18   S+   15:44   0:00 sudo docker run --rm alpine sleep 120
root      1920  0.0  0.2 150404 19936 pts/18   Sl+  15:44   0:00 docker run --rm alpine sleep 120
```

Doing a regular `kill` on either of these processes doesn't seem to do anything, the first tab's Docker process continued on happily.  When I did a `sudo kill -6` on the `sudo`'d process, that process was killed and the command in the first tab said "Aborted (core dumped)", but the non-`sudo`'d one continued on.  The container was still running, according to `docker container list`.  However, once process 1920 finished, the container was disposed of.

Running `docker stop` seems to take care of it all properly, will implement that tomorrow.

**Comment by rhliang** [comment]
I think I've got all of the important race conditions plugged now, and have tried using both `ctrl-C` and `kill -int` to kill the `docker_wrap.py` process.  In all my tests, the containers and volumes are correctly reaped.  Gonna merge this back into master now.

**Comment by rhliang** [comment]
Closed by 5123e10bf371f1ffe818a2b07981399972a94d64.

**Comment by donkirkby** [comment]
Check that an interrupt signal during the regular `--write` subcommand won't leave an orphaned container behind.

**Comment by donkirkby** [comment]
For testing, I created a large binary file that would be slow to copy in and out of the container:

    head -c1000000000 /dev/urandom > random-bits.bin

Then I used that as an input file, wrote a script that slept for 30 seconds and moved the big file to the output folder. Now I can test sending interrupt signals during read, run, and write.
