### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#721]
Python 2 will stop being supported in [2020], so we should plan for the transition. Perhaps we can clean up one app with each release.

* [x] Check that `archive` and `librarian` tests still pass.
* [x] Add Python 3 tests to TravisCI, running `archive` and `librarian`.
* [x] Pick the next module to work on, skipping stuff that will be deleted soon.

Django modules that are slated to be converted to Python 3 (i.e. stuff that is not going to be dropped during the 0.13 and 0.14 overhaul):

* [x] container
* [x] datachecking (although most of it will be dropped)
* [x] librarian (for Dataset)
* [x] metadata -- although this module can be dropped, the `KiveUser` and `AccessControl` classes should be retained and moved elsewhere
* [x] portal
* [x] stopwatch

Some final clean up tasks:
* [x] Convert `vagrant` script to match `vagrant_centos_python3`, and remove that.
* [x] Convert `vagrant_ubuntu` to Python 3.

### Config Changes
* Install Python 3.6 and switch Apache to launch it.

      sudo systemctl stop httpd
      sudo yum install centos-release-scl
      sudo yum install python36 python36-devel rh-python36-mod_wsgi
      sudo cp /opt/rh/httpd24/root/usr/lib64/httpd/modules/mod_rh-python36-wsgi.so /lib64/httpd/modules
      sudo cp /opt/rh/httpd24/root/etc/httpd/conf.modules.d/10-rh-python36-wsgi.conf /etc/httpd/conf.modules.d
      sudo mv /opt/venv_kive /opt/py27_venv_kive
      sudo python3.6 -m venv /opt/venv_kive
      sudo /opt/venv_kive/bin/python -m pip install --upgrade pip
      sudo /opt/venv_kive/bin/python -m pip install -r requirements.txt
      sudo sed -ie 's/python2.7/python3.6/' /etc/httpd/conf.d/001-kive.conf
      sudo systemctl start httpd

* Add `KIVE_SLURM_PATH` entry to `/etc/sysconfig/httpd`.

[2020]: https://pythonclock.org/

**Comment by donkirkby** [comment]
A few updates related to this issue:

* A team from RedHat published a detailed [porting guide] to Python 3. Some commentary on the guide recommended using the [future library] more than the guide does.
* The death date for Python 2 has been clarified. It is now [1 Jan 2020].

[porting guide]: https://portingguide.readthedocs.io/en/latest/
[future library]: https://pypi.python.org/pypi/future
[1 Jan 2020]: https://www.python.org/dev/peps/pep-0373/#maintenance-releases

**Comment by donkirkby** [comment]
Django has a [guide] for porting to Python 3.

[guide]: https://docs.djangoproject.com/en/1.11/topics/python3/

**Comment by donkirkby** [comment]
@wrpscott got `librarian` and `archive` tests to pass.
@rhliang tried `datachecking`, but we decided to leave it alone since it will be removed soon.

**Comment by donkirkby** [comment]
Let's use Python 3.6 for now. It's usually easier to install than 3.7.
There might be some hints in my live coding project's [TravisCI config]. I used tox and TravisCI's matrix feature. In order to make that work, you might need to mark all the unconverted modules with `skipIf()` decorators. That's not a bad way to mark what you have left to convert.

[TravisCI config]: https://github.com/donkirkby/live-py-plugin/blob/master/.travis.yml

**Comment by rhliang** [comment]
Django modules that are slated to be converted to Python 3 (i.e. stuff that is not going to be dropped during the 0.13 and 0.14 overhaul):

* [ ] container
* [ ] datachecking (although most of it will be dropped)
* [ ] librarian (for Dataset)
* [ ] metadata -- although this module can be dropped, the `KiveUser` and `AccessControl` classes should be retained and moved elsewhere
* [ ] portal
* [ ] stopwatch
