### ISSUE TITLE
Consider using the kernel inotify system to monitor file system changes

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#725]
Currently in Kive, we have idle tasks that periodically check file sizes by walking a subdirectory tree.
It could be of interest to perform certain actions only when a certain directory changes. The linux kernel supports this via the inotify subsystem.
There exists a python module that interfaces to it: https://github.com/dsoprea/PyInotify

**Comment by donkirkby** [comment]
Closing this issue, and adding the library as a suggestion on other issues.
