### ISSUE TITLE
Switch configuration details to environment variables

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#735]
~~Since converting the MiCall pipeline to a service in cfe-lab/MiCall#93 was pretty easy, do the same thing for the fleet manager.~~ (Switching to container runs.) Also consider moving the configuration details to environment variables instead of having a copy of `settings.py`.

**Comment by donkirkby** [comment]
Settings to convert to environment variables:

* [ ] purge thresholds
* [ ] list of admins

**Comment by donkirkby** [comment]
@rhliang, can you look at the changes to the default settings for this issue? Do a diff with your settings file and the test and production servers to see if there are any other settings that need environment variables.
One that I know is still missing is the `ADMINS` setting. Maybe a JSON format would be useful for that?

**Comment by rhliang** [comment]
Besides the purge thresholds and list of admins, here's everything I've spotted that doesn't already have a sensible default or an `os.environ.get` in comparing my `settings.py` file (which is tailored toward the default Vagrant machine) and production/testing:

- `DEBUG` (obviously)
- `EMAIL_HOST`
- `SERVER_EMAIL`
- `EMAIL_SUBJECT_PREFIX`
- `ALLOWED_HOSTS`
- `SECRET_KEY`
- `KIVE_PROCESSING_GROUP` (may not be relevant anymore)
- `SANDBOX_SETUP|DRIVER|BOOKKEEPING_PREAMBLE` (also may not be relevant anymore)
- `DEFAULT_CONTAINER` (though I think this may just have a sensible default now)
- `EXTERNAL_FILE_CHECK_HOURS`
- `CONFIRM_COPY_WAIT_MIN`
- `CONFIRM_COPY_WAIT_MAX`
- `CONFIRM_FILE_CREATED_WAIT_MIN`
- `CONFIRM_FILE_CREATED_WAIT_MAX`

**Comment by donkirkby** [comment]
Thanks for doing that review.
Isn't `SECRET_KEY` handled [here]?
I'll handle `EXTERNAL_FILE_CHECK_HOURS` in #750.
If you're willing to convert the rest, just assign this task to yourself.

[here]: https://github.com/cfe-lab/Kive/blob/d6a4885266e3242b959f2432e7b5637c09da2fb8/kive/kive/settings_default.py#L122-L125

**Comment by rhliang** [comment]
OK cool I guess I just don't have the most up-to-date commits on my local system.  I can work on converting the other stuff but won't assign it to myself until I'm able to get to it, as I have some other things to work on today.

**Comment by wrpscott** [comment]
The only other thing I would need for docker usage is KIVE_DB_HOST. I have a modded version of the settings I could commit.

**Comment by donkirkby** [comment]
The next release will still need to support the old pipelines on Singularity, but not Docker. I don't remember which of those scenarios uses the preamble, do you?

**Comment by rhliang** [comment]
Sorry -- I just realized they were originally intended for *Slurm* use, not Docker, so they may still be relevant.  I'll convert them.
