### ISSUE TITLE
Improve favicon.png

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#740]
I created an icon for the web site, since we didn't have one. James suggested some improvements:

* [x] Make the k a bit clearer. It would probably help to type it at a smaller font size instead of scaling the big one down. See if James can remember which font he used.
* [x] Reduce the number of dots, and try creating them at that size instead of scaling them.

**Comment by jamesnakagawa** [comment]
I think that it's [Archer](https://www.typography.com/fonts/archer/overview/). But I modified it, and at that size, you could use any slab serif.

**Comment by donkirkby** [comment]
Thanks, @jamesnakagawa. I found [Roboto Slab] and [Zilla Slab] that look pretty similar, and they're licensed under open licenses. Also, Google fonts looks pretty useful.

[Roboto Slab]: https://fonts.google.com/specimen/Roboto+Slab
[Zilla Slab]: https://fonts.google.com/specimen/Zilla+Slab

**Comment by jamesnakagawa** [comment]
Of those two I would use Roboto Slab in a boldface weight.

**Comment by jamesnakagawa** [comment]
I like! Nice one!!

**Comment by donkirkby** [comment]
Thanks for the suggestions, @jamesnakagawa.
