### ISSUE TITLE
Patched test case class breaks pytest

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#747]
I tried switching to running the tests with pytest, because it gives more details about failures, but I ran into a problem with integrity errors and foreign key constraints.

To see the error, try this command:

    pytest --ds kive.settings_test_pg \
    archive/tests.py::StateMachineActualExecutionTests::test_long_output \
    archive/tests.py::TopLevelRunTests::test_usual_run

The problem seems to be caused by our patched version of `TransactionTestCase`: [`SlurmExecutionTestCase`]. If I replace that with a basic `TestCase`, then the error goes away.

We could ignore this problem by sticking with unittest, but I'd prefer to run with pytest.

[`SlurmExecutionTestCase`]: https://github.com/cfe-lab/Kive/blob/v0.12.2/kive/kive/tests.py#L134

**Comment by donkirkby** [comment]
Try switching again after #752 is done, because that will probably remove the `slurmlib` package.

**Comment by wrpscott** [comment]
[root@kive kive]# sudo -u wscott -E bash -c "pytest --ds kive.settings_test_pg"
============================================= test session starts =============================================
platform linux2 -- Python 2.7.5, pytest-4.6.6, py-1.8.0, pluggy-0.13.0
Django settings: kive.settings_test_pg (from command line option)
rootdir: /kivesrc/kive, inifile: pytest.ini
plugins: django-3.7.0

pytest now works perfectly. Only tested under python2.
