### ISSUE TITLE
apache changes permissions on logfiles upon roll-over

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#748]
The fleet failed to run properly (step_helper failed) after a restart because of an incorrect permission on Kive.log (missing group write permissions)
The issue occurred after/during a rapid rollover of log files. This issue may be related to #683 .
Note: there are 999 log files, which means probably means that the rollover is slow?

**Comment by donkirkby** [comment]
I think this won't be a problem with the changes to the logging configuration in v0.13.
