### ISSUE TITLE
Run a pipeline in a container

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#751]
Now that issue #739 has added a simpler pipeline configuration based on Singularity, we'd still like to support the old style of pipeline where a developer can wire a bunch of scripts together into a pipeline.

  * Upload a zip/tar.gz file with scripts in it.
  * Use the pipeline UI to wire inputs and outputs between scripts.
  * Save pipeline as a `pipeline.json` file in the tar.gz file with the scripts.
  * Launch the pipeline with a default Singularity image, plus the tar.gz file mounted on `/mnt/bin`, plus a driver script that reads the `pipeline.json` file and executes the steps.
  * The advantage is that this all runs as a single Slurm job, and the accounting is much simpler.
  * You can also migrate a pipeline from development to test to production by downloading the tar.gz file that includes the `pipeline.json`, and uploading it to another Kive server. A Kive container can be either a Singularity image or a tar.gz file. The tar.gz file is a layer on top of the default Singularity image.
  * When you upload a new tar.gz container without a `pipeline.json`, it can copy the `pipeline.json` from the previous revision in the container family.

Implementation steps:
* [x] Add parent container to `Container` model. That means that the child's container file will be extracted and mounted under the parent's `/mnt/bin` folder. Then the parent container runs.
* [x] Add tests for validating container file contents.
* [x] Use the existing pipeline builder to submit a `pipeline.json` file to the server.
* [x] Remove unused fields from `pipeline.json`.
* [x] Add an edit option for input nodes, and remove structure field.
* [x] Write the updated `pipeline.json` file into a zip container.
* [x] Read and write tar containers.
* [x] Update method magnets while typing inputs and outputs.
* [x] Hint how to enter multiple inputs and outputs.
* [x] Add default config menu to pipeline, and write it to `pipeline.json`.
* [x] Fix broken upload for container files.
* [x] Investigate warning about missing temporary file in `container.tests.ContainerApiTests.test_create_singularity()`.
* [x] Filter parent container list to only include singularity containers.
* [x] Launch each step with `singularity exec`, based on the steps in the container's `pipeline.json` file.
* [x] Create an app when writing archive content.
* [x] Test running pipelines.
* [x] Load the pipeline editor, even when the `pipeline.json` contents are invalid.
* [x] Update MD5 whenever `pipeline.json` is updated.
* [x] Check container and parent MD5's before launching a run.
* [x] Check input MD5's before launching a run.
* [x] Let user upload or revise containers with invalid pipelines, but display a warning, and don't create an app. That will stop them from launching.
* [x] Submit pipeline button splits into "Save" and "Save as new revision" (which prompts for tag and description).
* [x] Convert old pipelines to child containers.
* [x] Update developer documentation on how to create a pipeline.
* [x] Stop editing a pipeline after it's been published, or use copy on write. Something to make all published runs reproducible.
* [x] Create separate folders for each step, to avoid output name collisions.
* [x] Add child containers to removal plan.
* [x] Log to stderr if a run fails due to a bad MD5

Example JSON:
The `pipeline.json` file wouldn't hold the list of files. It would just have everything in the `pipeline` entry. The full JSON would appear in the GET response to `/api/containers/123/contents`.

```
{
    "files": [
        "filter_quality.sh",
        "helper.py",
        "lib/antigravity.py"],
    "pipeline": {
        "kive_version": "0.14",
        "default_config": {
            "parent_family": "kive-default",
            "parent_tag": "v1.1",
            "parent_md5": "225a63213afdfd2e2659e9f9c1a3b695",
            "memory": 100,
            "threads": 1
        },
        "inputs": [
            {
                "dataset_name": "quality_csv",
                "x": 0.426540479529696,
                "y": 0.345062429057889
            }
        ],
        "steps": [
            {
                "driver": "filter_quality.sh",
                "inputs": [
                    {
                        "dataset_name": "quality_csv",
                        "source_step": 0,
                        "source_dataset_name": "quality_csv"
                    }
                ],
                "outputs": ["bad_cycles_csv"],
                "x": 0.501879443635952,
                "y": 0.497715260532689,
                "fill_colour": ""
            }
        ],
        "outputs": [
            {
                "dataset_name": "bad_cycles_csv",
                "source_step": 1,
                "source_dataset_name": "bad_cycles_csv",
                "x": 0.588014776534994,
                "y": 0.640181611804767
            }
        ]
    }
}
```

**Comment by rhliang** [comment]
Been thinking about this today, sifting through Container code to get a better idea of how a Pipeline would be represented in JSON.  Can anyone see anything missing from this tentative representation:

```
Pipeline JSON format is a dictionary (or "object" I guess) with fields "inputs", "outputs", and "steps", each of which is a list

inputs: a list of input names

steps: each step is represented as
 - script
 - invocation (maybe we can assume this is standardized like old Kive scripts)
 - inputs (tuples: step num and name)
 - outputs (names)

outputs: each output represented as
 - name
 - source (tuples: step num and name)
```

**Comment by donkirkby** [comment]
The `pipeline.json` format should also have support for the automated configuration described in #749, as well as a link to the name and MD5 of a Singularity container that it will run in. That will let the archive container file be copied from one Kive server to another without requiring a lot of setup steps.
Launching an archive container should probably use `singularity exec` so the Singularity container doesn't need explicit support for running pipelines. The `run_pipeline.py` script should be part of the archive container.

**Comment by rhliang** [comment]
Having looked a little more, I am wondering if we should store some of the UI representation information like (x,y) coordinates etc in case we ever want to edit or make a new version of it.  If so, in addition to the above info:

```
metadata: an object with fields
 - default container name
 - default container MD5
 - default number of threads
 - default memory allocated

steps: in addition to the above, each step has
 - x
 - y
 - fill colour
```

I don't think I'm qualified to dig much into the Javascript/Typescript code that defines the UI but I am hoping that much of it could be repurposed -- if our API serves it a list of files in the uploaded tarfile, it could hopefully be handled by modifying the code that makes the menu to select/produce Method nodes in the existing Pipeline UI.

If no one objects I may just start digging into producing a `run_pipeline.py` for the default container to use.

**Comment by rhliang** [comment]
I think this covers everything that we would need to actually carry out the pipeline:

```
{
    "default_config": {
        "container_name": "kive-default",
        "container_md5": "225a63213afdfd2e2659e9f9c1a3b695",
        "memory": 100,
        "threads": 1
    },
    "inputs": [
        {
            "dataset_idx": 1,
            "dataset_name": "quality_csv",
            "x": 0.426540479529696,
            "y": 0.345062429057889
        }
    ],
    "steps": [
        {
            "driver": "filter_quality.sh",
            "invocation": "bash filter_quality.sh {input1} {output1}",
            "inputs": [
                [0, "quality_csv"]
            ],
            "outputs": ["bad_cycles_csv"],
            "x": 0.501879443635952,
            "y": 0.497715260532689,
            "fill_colour": ""
        }
    ],
    "outputs": [
        {
            "dataset_name": "bad_cycles_csv",
            "source": [1, "bad_cycles_csv"],
            "x": 0.588014776534994,
            "y": 0.640181611804767
        }
    ]
}
```

**Comment by donkirkby** [comment]
I suggest we avoid a custom invocation field until we need it. Can't we just use `driver input1 input2 output1 output2` as the standard invocation?
How about writing all the intermediate output files to `/mnt/output` as `step1_output1`, and then renaming any run outputs to `output1` after the last step finishes?

**Comment by rhliang** [comment]
Yeah, sounds good, let's go with that.

**Comment by donkirkby** [comment]
I have a cunning idea! :smiling_imp:
`run_pipeline.py` doesn't have to run inside the container. The `runcontainer` command could have logic to handle archive containers, and it could call `singularity exec` separately for each step in the pipeline. The benefit of this is that the singularity container wouldn't require Python, and the logic for running a pipeline stays in Kive.

Also, I suggest we write the Kive version into `pipeline.json`. I think this has two uses:
1. It's a reasonable sanity check on the `pipeline.json` file. It's remotely possible that a developer could create an archive that included some other file named `pipeline.json`. Kive could just reject that archive if it doesn't find a `kive_version` field in `pipeline.json`.
2. We might need it to support backward compatibility if we change the pipeline interface in the future.

**Comment by rhliang** [comment]
Another small edit: inputs don't need a `dataset_idx` field, they will be listed in their correct order.

**Comment by donkirkby** [comment]
I suggest we tweak the parent configuration in `pipeline.json`. Change this:

    "default_config": {
        "container_name": "kive-default",
        "container_md5": "225a63213afdfd2e2659e9f9c1a3b695",
        "memory": 100,
        "threads": 1
    },

To this:

    "default_config": {
        "parent_family": "sample",
        "parent_tag": "basic",
        "parent_md5": "8dab0b3c7b7d812f0ba4819664be8acb",
        "memory": 100,
        "threads": 1
    },

This clarifies that it's for the parent, not the archive container. It also matches the fields on the container - there is no name, only a tag and a family name.

**Comment by donkirkby** [comment]
I'm getting a warning when the unit test suite shuts down:

>Exception OSError: (2, 'No such file or directory', '/tmp/tmpZsW3ZO.upload') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7f8103bc4780>> ignored

It happens when I run the [`ContainerApiTests.test_create_singularity()` test][test]. I traced through the code, and found that Django writes an uploaded file into a temporary file when a request's content length is over 2621440 bytes, or 40 times 64KB. When that temporary file gets [moved] into the upload directory, the `NamedTemporaryFile` gets confused, and complains that it can't find the file when it tries to delete it.

[test]: https://github.com/cfe-lab/Kive/blob/817fb78cee2badfc2c35ca66dad341b2250acfa9/kive/container/tests.py#L222
[moved]: https://github.com/django/django/blob/1.11.18/django/core/files/storage.py#L338

**Comment by donkirkby** [comment]
WOOT!
