### ISSUE TITLE
Remove old runs and pipelines

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#752]
Once all the old pipelines are converted to child containers in issue #751, we can remove all the code to support the old pipelines:
* [x] runs
* [x] fleet and sandbox
* [x] docker and slurmlib
* [x] pipelines, methods, transformations, and code resources
* [x] compound datatypes
* [x] delete orphaned datasets from MD5 conflicts
* [x] delete orphaned datasets from intermediate steps that weren't wired to pipeline outputs
* [x] add tests for removal plan
* [x] ~~remove `@types/jquery` from `package.json`~~ Can't remember why we wanted this, so postpone it for now.

**Comment by donkirkby** [comment]
What should we do about intermediate datasets that were not wired to pipeline outputs? They got recorded as datasets in the old runs, but they would not get created in the converted container runs.

Should we just delete the datasets? What about the MD5 conflict datasets? Should we delete those, too?

**Comment by rhliang** [comment]
I think that's OK, considering they would have gotten purged in pretty short order otherwise anyway.

**Comment by dmacmillan** [comment]
I wrote a django management script to handle orphaned datasets, which should clear the last two things off this list. The last thing to do would now be to update the test server where kive is running with the `drop_pipeline` branch. I think the test server is called `bulbasaur` but I still don't have access to it.

**Comment by donkirkby** [comment]
Closed by 79617aeea5fbd39f1d4cd8a5705b7e0be2a8199a.
