### ISSUE TITLE
Make reruns easier

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#754]
If an output from run A is used as an input to run B, then that input will eventually get purged. Once that happens, you can't rerun run B by just clicking the Rerun button. Instead, you have to rerun run A to regenerate its output, then create a new version of Run B on the Container Analysis page.

Suggested fix: clicking on the rerun button checks for all the inputs, and generates new copies of runs A and B with a slurm dependency between them. It will also need to support output placeholders so the output from run A can be linked as an input to run B.

It might also be helpful to have some kind of rerun link between runs. That could be used to generate a report of the differences between an original run and its rerun. It could also be used to find the input for rerun B in the outputs of rerun A.

* [x] add link from rerun to original run
* [x] fill in existing inputs from rerun
* [x] look for purged inputs from reruns of their source run
* [x] schedule nested reruns with dependencies
* [x] ~~check rerun inputs before purging a dataset~~ Not worth checking for now.
* [x] basic comparison of outputs, just "Changed: Y/N"

**Comment by donkirkby** [comment]
Here's my plan for making reruns easier:
1. Add a link from the new run to the old run that it's copying.
2. When you request a rerun through the API, you don't fill in any input datasets, just the link to the old run.
3. The server goes through all the inputs of the old run, and creates matching `ContainerDataset` records for the new run. If any of the inputs have been purged, it recursively creates `ContainerRun` reruns to reproduce them, and doesn't create `ContainerDataset` records for them. When looking for old inputs, it has to navigate rerun links to check if purged datasets have already been reproduced.
4. The server then schedules Slurm jobs for all of the `ContainerRun` reruns it created, with dependencies between them.
5. When `runcontainer` starts a run, it looks for missing `ContainerDataset` records, navigates the rerun links to find the new datasets, and creates the missing `ContainerDataset` records before launching the run.

**Comment by rhliang** [comment]
That looks OK to me.  Can we protect the new stuff from being deleted again while it's needed for a pending run?

**Comment by donkirkby** [comment]
Good suggestion, I added it to the check list.

**Comment by donkirkby** [comment]
I have one item left for improving reruns, but I don't think it's worth doing.
The idea was to check whether a dataset is going to be consumed by a rerun before purging it. There are two problems:
1. It's not easy or efficient to check.
2. It's very unlikely to be necessary.

Because a run can be rerun, and then the rerun can be rerun, you can't write a single SQL query to look for a complete set of related reruns. Standard SQL doesn't do tree structures. That means we'd have to navigate the tree, running SQL queries at every level. Depending on how many reruns we have and how deeply nested they are, that could get slow. To avoid this, I think we'd need to add a many-to-many relationship for all the nested reruns or rerun datasets.
So is it worth it? I don't think so. A rerun output could get purged between the time the producer rerun finishes and the consumer rerun starts. Unless the consumer rerun needs way more resources than the producer and has to wait for a Slurm allocation, there should be hardly any gap between those two runs. If datasets are being purged that quickly, we'll have many problems.
