### ISSUE TITLE
Management command to move container files

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#756]
The existing container files are stored in the `CodeResources` folder, but the new release stores them under `Containers`. We need a management command to move the files and update the paths in the database, similar to `convert_docker_images`.
We can also get rid of `convert_docker_images`, since we're not using docker anymore.

**Comment by rhliang** [comment]
I've gotten a command working but it has the flaw that if a file that is outside the `Containers` directory shares a name with something that already is in the `Containers` directory, it may overwrite the existing copy.  I need to be more clever about checking for a matching file first.

**Comment by donkirkby** [comment]
The `FileField` is smart enough to handle duplicate names when you do a normal upload, so maybe instead of moving the file, you should just upload it back to the same record. That should write it to the `Containers` folder, and give it a unique suffix if needed. Then you just have to delete the old file.

**Comment by rhliang** [comment]
That's probably wise, I was trying to avoid that because one of their developers seemed to not think highly of that method in one of their issues, but it still seems like the safest way.

**Comment by donkirkby** [comment]
The [comment] was:

>People are doing crazy stuff like opening the whole file and saving it back using the save() method (since save and delete are the only methods provided in docs).

I agree that it's more expensive to copy the file than to move it and update the path, but this isn't a task that will be run more than once. I think the slower execution is justified by having simpler code that is less error prone.

[comment]: https://code.djangoproject.com/ticket/15590#comment:2
