### ISSUE TITLE
Add more validation when uploading an archive container

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#763]
We have basic support for running archive containers, but we could be more helpful for junior developers.

* [x] ~~Reject the upload if the archive is empty.~~ this is a subset of "Reject the upload if there are no driver files."
* [x] Filter the list of driver files to only include those with a `#!` prefix on the first line.
* [x] Reject the upload if there are no driver files.
* [x] Display the contents after upload.

**Comment by rhliang** [comment]
Just checking, by "Reject the upload if the archive is empty" do we mean that no file is uploaded or do we mean that there is a valid tar/zip file but it has no contents?  If so, that's a subset of "Reject the upload if there are no driver files"; do we want to have separate error messages for both?

**Comment by donkirkby** [comment]
Good point. I'm fine with the check for driver files covering both scenarios. I don't think we need a separate message. However, you may need a separate test case for a zero-length file with a `.zip` or `.tar` file name. That might be covered by the current validation that the archive is a valid archive, I'm not sure.

**Comment by rhliang** [comment]
OK, I'll edit the list.

**Comment by rhliang** [comment]
By "display the contents after upload" do we mean right after the file has been selected or after the container has been submitted?

**Comment by donkirkby** [comment]
After the container has been submitted. I was thinking we could display a couple of comma-separated lists on the `container_update` page: a list of drivers and a list of other scripts.

**Comment by donkirkby** [comment]
What's the status on this issue, @rhliang?

**Comment by rhliang** [comment]
OK yes, I confirmed that this is all on a local branch, and that's why no commit numbers are showing up here.  Now that the release is done, shall I just merge my branch into master?

**Comment by donkirkby** [comment]
Yes, please, @rhliang. If it's a local branch, you can rebase it onto master.
