### ISSUE TITLE
Dataset filter is not applied

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#775]
Steps to reproduce:

1. Use a database that has at least one uploaded dataset that is over a month old.
2. Open a new tab in your browser, and navigate to the datasets page. The default filters are for uploaded datasets and less than one month old.
3. Look at the number of datasets found.
4. Click the search button with the magnifying glass on it.

Expected behaviour: the number of datasets should stay the same.

Actual behaviour: the number of datasets drops, because the date filter isn't applied when you first visit the page.

**Comment by rhliang** [comment]
Recapitulating what we discussed on Slack: @donkirkby found that the issue appears to be this code: https://github.com/cfe-lab/Kive/blob/master/kive/librarian/templates/librarian/datasets.html#L32-L40

The problem appears to be that the call to `table.filterSet.add` causes a query to run that is still running at the time the call to `table.filterSet.addDate` happens, causing that query to fail.  Skipping that first query (it will run properly when the second call is made anyway) should fix it.

I'm unable to easily reproduce the problem on my workstation, as I don't have enough datasets to cause the first call to be slow enough that it's still running when the second call happens, but making the suggested change doesn't seem to break anything at least.  I'll push this change tomorrow after we discuss a way to verify this change.

**Comment by rhliang** [comment]
Scratch that, I found that I was able to reproduce the problem by using a private browser tab that would not retain my filter settings.  I'll push my commit and close.
