### ISSUE TITLE
Multiple search filters are ignored

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#776]
If you add more than one filter at a time, search pages will ignore all except the first filter.

Steps to reproduce:

1. Go to a page with a lot of data so it has a noticeable delay when you search.
2. Remove all the filters so you see a complete list.
3. Add the filter "a" and wait for the results. (Record how many matches you found.)
4. Add a second filter "b" and wait for the results. (Record how many matches you found.)
5. If the number of matches is the same in steps 4 and 5, choose two different filters to use.
6. Remove all the filters and wait for the complete list.
7. Quickly add the two filters "a" and "b" without waiting for the results of the first filter.

Expected behaviour: the number of matches in step 7 should be the same as the number of matches in step 4.

Actual behaviour: the number of matches in step 7 is the same as the number of matches in step 3. (The second filter gets ignored, because there is an active AJAX request for the first filter.)

See if we can cancel the first request when another request comes in, or at least don't ignore the later filter requests.

**Comment by rhliang** [comment]
For my own edification: it looks like the relevant code is here?

https://github.com/cfe-lab/Kive/blob/e7a5d05b348ae8c709103f64dd31d102c0558512/kive/portal/static/portal/permissions.js#L355-L360

**Comment by rhliang** [comment]
Assuming that I understood my own fiddling with the Chrome developer tools, commenting out the `return` and uncommenting out the `abort` and `= undefined` lines seems to address the problem, although there is a slightly uncomfortable intermediate state where "Failed to reload table" appears (presumably this is from aborting the query coming from the first filter).  Seems like there should be a tidy way to configure the "failure" message when it comes from refining a filter as opposed to an actual failure, I'll look into that with my limited JS ability.
