### ISSUE TITLE
Admin user can't download private sample

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#792]
Steps to reproduce:

1. Set up two users: Alice and Bob, where Alice has staff status.
2. Upload a dataset as Bob, and don't grant access to anyone else.
3. Log in as Alice.
4. Go to the datasets page. You should not see Bob's dataset.
5. Click the lock icon to unlock the admin tools. You should now see Bob's dataset.
6. Click on Bob's dataset. You should see the dataset details page.
7. Click the download button.

Expected behaviour: the download is successful.

Actual behaviour: 404 - page not found.

**Comment by dmacmillan** [comment]
@donkirkby I just pushed a fix for this. It works for me, let me know how it goes for you!

**Comment by donkirkby** [comment]
Tested successfully, @dmacmillan. BTW, [commit messages] can mark an issue as closed.

[commit messages]: https://github.blog/2013-01-22-closing-issues-via-commit-messages/
