### ISSUE TITLE
Ubuntu vagrant installation contains interactive component

### ISSUE THREAD

**Issue by dmacmillan** [cfe-lab/Kive#824]
When installing Kive for `vagrant_ubuntu`, the installation haults during the installation of Singularity. A text prompt pops up asking for the user to type Yes/No. The display gets messed up and the input doesn't work no matter what you type. I was able to work around the issue by including:

    export DEBIAN_FRONTEND=noninteractive

in `bootstrap.sh`

**Comment by donkirkby** [comment]
Strange. Go ahead and commit your workaround, @dmacmillan.

**Comment by dmacmillan** [comment]
Ok, I will push it to a `hotfix` branch and then create a PR. But first I'll need permissions for this repository.
