### ISSUE TITLE
MEDIA_ROOT default in settings.py is variable

### ISSUE THREAD

**Issue by dmacmillan** [cfe-lab/Kive#829]
The `MEDIA_ROOT` variable in `kive.settings` gets set based on a users home directory (right now it's `~/data/kive`) if the environment variable is not set (which in the case of the `vagrant` user and the `kive` user it is not).

This means that when resolving the path for `FileField` instances (actually uses `FieldFile` object) it constructs a path based on the user's home directory. 

It **should** construct a path regardless of user that points to `KIVE_MEDIA_ROOT` in `vagrant_ubuntu/envvars.conf`. If we set the default value in `kive/settings.py` to be `/var/kive/media_root` as it is in envvars, then we avoid the variable path construction and we can actually remove the export statement in envvars. The same goes for `KIVE_STATIC_ROOT`.

I went over it with @rhliang and @neganp and we have all agreed that this would be a desirable change.

**Comment by donkirkby** [comment]
I set that default thinking that most developers would run Kive in their host system, and have the media root folder under their home directory.

What about writing `KIVE_MEDIA_ROOT` to the `/etc/environment` file, so that all users get it? You could put that in the `bootstrap.sh` script.

**Comment by dmacmillan** [comment]
That would also work, one caveat I was going to say about the original solution is that if you are logged in as the vagrant user, by default you will not have access to `/var/kive`. There is also an easy solution to this which would be to grant write permissions via the `kive` user.

**Comment by donkirkby** [comment]
I think that will still be a problem with my solution. You could add the `vagrant` user to the `kive` group in the `configure_vagrant_user.sh` script.
