### ISSUE TITLE
Test settings are obsolete

### ISSUE THREAD

**Issue by nathanielknight** [cfe-lab/Kive#952]
[`kive.settings_test`](https://github.com/cfe-lab/Kive/blob/master/kive/kive/settings_test.py) contains settings overrides to run tests with an in-memory SQLite database (which should be faster than a PostgreSQL database). However, the test run fails with an `django.db.utils.OperationalError` while running migrations to set up the test database.

The failure is in `archive/migrations/0109_drop_methodoutput_execlog_runstep.py`.

This settings file should either be investigated (if the test speedup is desirable enough) to see why SQLite isn't a suitable database back end, or removed.

**Comment by donkirkby** [comment]
We haven't used the SQLite tests in years, and the test suite is fast enough right now. I suggest we remove the old settings.
